### ISSUE TITLE
关于LCCKForceReconnectSessionBlock读写权限.

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#100]
@property (nonatomic, copy, readonly) LCCKForceReconnectSessionBlock forceReconnectSessionBlock;
public var forceReconnectSessionBlock: LCCKForceReconnectSessionBlock! { get }
v0.7.15 这个Block只有get 权限. 在Swift类中.无法修改.
新版本中,能否取消只读?

**Comment by ChenYilong** [comment]
已经修改 v0.7.17 https://github.com/leancloud/ChatKit-OC/commit/3160070655eff3a29c0151db3cdd5227a2ee0932
