### ISSUE TITLE
新账号首次登陆提示“当前账号已在其他设备登录”

### ISSUE THREAD

**Issue by mikumaycry** [leancloud/ChatKit-OC#105]
ChatKit-OC的demo中开启了单点登录，使用clientID作为tag，但随机输入一个新的clientID（openssl生成的），服务端总是返回
```
sessionMessage {
      code: 4111
      reason: "SESSION_CONFLICT"
    }
```
新建的clientId应该是没有人登录过的，但却提示session_conflict
这个是bug吗？

**Comment by zzgo** [comment]
同样有这个问题。然后每次都强制登录

**Comment by ChenYilong** [comment]
v.0.7.19版本中已经修复掉了，请更新下
