### ISSUE TITLE
更友好的入门文档

### ISSUE THREAD

**Issue by nicecui** [leancloud/ChatKit-OC#117]
https://github.com/leancloud/docs/issues/1575
https://github.com/leancloud/docs/issues/1578

**Comment by ChenYilong** [comment]
Tip:

 1.  加上如何 import；
 2. 介绍 `LCChatKitExample` 类里的胶水函数如何调用；

**Comment by nicecui** [comment]
ChatKit 提供了一个快速集成的演示类 LCChatKitExample，路径如下：
- 在 -[AppDelegate didFinishLaunchingWithOptions:] 等函数中调用下面这几个基础的入口胶水函数，可完成初步的集成。
- 胶水代码中包含了特地设置的 #warning，请仔细阅读这些 warning 的注释，根据实际情况调整代码，以符合你的需求。

**建议将上面的话修改为：**
ChatKit 提供了一个快速集成的演示类 LCChatKitExample，路径如下：
https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit-OC/Example/LCChatKitExample.m

- 可以将 LCChatKitExample 拖入到你的项目中，在 -[AppDelegate didFinishLaunchingWithOptions:] 等函数中调用下面这几个基础的入口胶水函数，可完成初步的集成。
- 也可以参考胶水函数中的代码，自行撰写逻辑。
- 胶水代码中包含了特地设置的 #warning，请仔细阅读这些 warning 的注释，根据实际情况调整代码，以符合你的需求。

**Comment by ChenYilong** [comment]
嗯，👍。

**Comment by nicecui** [comment]
https://leancloud.cn/docs/chatkit-ios.html#使用方法
4. 调用 -[[LCChatKit sharedInstance] closeWithCallback:] 关闭 LeanCloud 的 IM 服务，结束聊天。
这里的第四步应该放到最后一步

**Comment by nicecui** [comment]
5. 实现 -[[LCChatKit sharedInstance] setFetchProfilesBlock:]，设置用户体系，里面要实现如何根据 userId 获取到一个 User 对象的逻辑。ChatKit 会在需要用到 User 信息时调用你设置的这个逻辑。 LCCKUserSystemService.h 文件中给出了例子，演示了如何集成 LeanCloud 原生的用户系统 AVUser。

 这个应该是第四步，另外 `LCCKUserSystemService.h` 最好加上链接链到 Github

**Comment by nicecui** [comment]
https://leancloud.cn/docs/chatkit-ios.html#最近联系人界面
调用这个方法后会崩溃，原因是没有设置用户体系，所以需要在这一步的前面再解释一下如何设置用户体系。

**Comment by nicecui** [comment]
文档里面的「使用 ChatKit 大体有几个步骤」，每一个步骤都应该在下方进行详细的说明。
这样我就不用遇到问题之后来回翻文档试图寻找答案了。

**Comment by nicecui** [comment]
https://leancloud.cn/docs/chatkit-ios.html#由最近联系人进入聊天界面
https://leancloud.cn/docs/chatkit-ios.html#聊天界面

这里的「聊天界面」放到「由最近联系人进入聊天界面」的前面

**Comment by nicecui** [comment]
https://leancloud.cn/docs/chatkit-ios.html#由最近联系人进入聊天界面
这里的四种响应操作要说明由 [LCChatKit sharedInstance] 来调用。

**Comment by nicecui** [comment]
有很多在 App 生命周期内只需要调用一次的方法，也需要写清楚。

**Comment by nicecui** [comment]
先找出来这么多

**Comment by ChenYilong** [comment]
以上建议中，除了“建议贴出代码的在线链接”外，均已修改。

**Comment by myleslee** [comment]
文档 views/chatkit-ios.md 如何与这里的 README 保持同步？

**Comment by ChenYilong** [comment]
人肉提PR

**Comment by ChenYilong** [comment]
现在已经很友好了，如果还有建议，再重新打开。
