### ISSUE TITLE
如何在会话列表插入系统,机器人消息.

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#118]
1. ChatKit Version：0.7.16
2. Language：Swift
3. Issue Type:Q-A

我想在ConversationList中插入和基本消息类型无关的消息,由我们系统发送.比如qq发给用户新闻,微信发给用户公众号更新等等.

conversationListService可以自定义Cell.插入一条非IM的Cell.也是可行的.这样已经很接近最终的需求了.但是我不知道这样的data怎么和ChatKit中的会话列表本地数据库中的缓存结合起来.

我想到了一个方案,想请问一下可行性.记得leanCloud 实时消息里有机器人的概念.通过自己的服务器向用户发送一种自定义的消息,通过conversationListService自定义cell,同时达到直接走ChatKit大部分功能的目的.比如:数据库缓存,和一般的会话列表共存.

**Comment by ChenYilong** [comment]
你可以使用系统消息来实现该功能，

创建一个系统对话，需要通过REST API 创建，详情见文档： [《创建一个对话》]( https://leancloud.cn/docs/realtime_rest_api.html#创建一个对话 )  ,发送一个系统消息也是通过REST-API发送，详情见文档  [《系统对话给用户发消息》]( https://leancloud.cn/docs/realtime_rest_api.html#系统对话给用户发消息 ) ，修改系统对话时，也必须使用REST-API或者直接到控制台修改。APP不支持修改。



参考这里的讨论 https://github.com/leancloud/ChatKit-OC/issues/54

**Comment by ChenYilong** [comment]
如何查询机器人消息，这个可能能帮到你：https://github.com/leancloud/objc-sdk/pull/130
