### ISSUE TITLE
请求增加发送信息时的回调

### ISSUE THREAD

**Issue by sunlei053667** [leancloud/ChatKit-OC#119]
## Base Info for this issue 

这个问题是为了解决黑名单问题，黑名单问题用LeanEngine写云函数后发现发送消息时会比较慢，在每次发送消息的时候，云函数都会去检查是否发送者被加入黑名单。

因此考虑从客户端解决，客户端会缓存一个黑名单列表，就是自己被哪些人加入黑名单。这个列表会通过推送的形式进行更新，即有人把自己加入黑名单了，对方会发送推送消息过来更新自己的本地缓存。

现在由于列表已经在本地了，只需要在发送的时候检查本地缓存，即可曲线解决黑名单问题，希望能够开放出一个发送消息时的回调接口。

 1. ChatKit Version：0.7.15
 2. App-ID: 无
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Enhancement（希望能支持一个新需求）

##  Please help me in this way.

增加一个回调接口，就是在点击发送消息的时刻，能够调用这个回调，让我能够增加判断用户是否在我的黑名单缓存列表中。

**Comment by ChenYilong** [comment]
你的意思是A把B列为黑名单，希望B不能给A发送消息？

我需要把B发送消息的行为添加一个hook给你？

**Comment by sunlei053667** [comment]
对的，完全正确

**Comment by ChenYilong** [comment]
UI上你打算如何展示？跟断网下发送消息失败一样？如果不是这样，请详细描述下你希望达到的效果。

**Comment by sunlei053667** [comment]
对，就是一个红色感叹号就行，额外的alert或者toast我自己加就可以了，这个hook只要带一个参数就是LCCKConversationViewController，我就可以自己定制一些额外的界面。另外这个消息不往服务器发送，就是本地吞掉，不要往外发。

**Comment by sunlei053667** [comment]
能否帮出一个enhancement，因为产品快要上线了，有点急，多谢多谢～

**Comment by ChenYilong** [comment]
这是新的API ，对应PR见：https://github.com/leancloud/ChatKit-OC/pull/154

**Comment by ChenYilong** [comment]
v0.8.0已经发布，如果对这个API还有问题，再重新打开issue。

**Comment by sunlei053667** [comment]
为什么我在用这个回调的时候，第一次进对话窗口也会调用这个hook。请问我如何区分，我是正在发消息还是正在进入这个对话？
