### ISSUE TITLE
第一次集成使用会 crash

### ISSUE THREAD

**Issue by jwfing** [leancloud/ChatKit-OC#12]
LCCKUserSystemService.m L252
    for (id<LCCKUserModelDelegate> user in users) {
        self.cachedUsers[user.userId] = user;
    }

**Comment by ChenYilong** [comment]
升级了0.0.5版本，再试试。

**Comment by jwfing** [comment]
错了，是我没有扩展 LCCKUserModelDelegate 这个接口。
