### ISSUE TITLE
(Q-A)消息类型的配置

### ISSUE THREAD

**Issue by sunlei053667** [leancloud/ChatKit-OC#120]
## Base Info for this issue 

请问，发送消息类型，如果只要照片、拍摄、改背景三个功能，在哪里进行配置，谢谢！
![image](https://cloud.githubusercontent.com/assets/8157807/18948692/afe3ed0a-866a-11e6-8a6e-c7f6e44f5854.png)

 1. ChatKit Version：0.7.15
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS9
 5. Prototype（是否是真机）：YES
 6. Issue Type：Q-A

**Comment by ChenYilong** [comment]
文档中有详细描述：

主要是删除对应类：

https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit%20自定义业务.md#自定义输入框插件


另外删除位置这个插件，你需要删除这行代码

 ```Objective-C
    [LCCKInputViewPluginLocation registerSubclass];
 ```

**Comment by sunlei053667** [comment]
好的，非常感谢，问题已经解决。

补充一点给其他有类似需求的，我是把Demo里面Class/Module/Customize中不需要的组件整个文件夹删除，然后更改了剩余其他组件的类型值，这个类型值必须从1开始定义，如果你删除的恰巧是1的话，需要把其他组件的类型值从1开始重新定义。
static LCCKInputViewPluginType const LCCKInputViewPluginTypeConversationBackground = 1;
