### ISSUE TITLE
能否手动根据conversation id 进入聊天页面

### ISSUE THREAD

**Issue by lanstonpeng** [leancloud/ChatKit-OC#137]
ChatKit Version：0.7.17

**Comment by ChenYilong** [comment]
可以，聊天页面的初始化是独立于最近对话列表的，你可使用conversationId初始化一个聊天页面，然后就可以push或present，初始化方法参考：

https://github.com/leancloud/ChatKit-OC#聊天界面

**Comment by ChenYilong** [comment]
可以实现，已经提供方案，如果还有疑问，再重新打开吧。
