### ISSUE TITLE
ConversationViewController 里面 tableView 和 navigationbar 重合了

### ISSUE THREAD

**Issue by jwfing** [leancloud/ChatKit-OC#14]
![screen shot 2016-07-08 at 3 59 27 pm](https://cloud.githubusercontent.com/assets/985038/16681043/0b497a84-4525-11e6-99dc-20a09ccdef99.png)

**Comment by ChenYilong** [comment]
把版本更新到0.0.5吧，我看UI还是0.0.4的

**Comment by ChenYilong** [comment]
把怎么初始化的 navigation 对象以及怎么 push 进来的代码帖一下。

参考：

 
 ```Objective-C
LCCKConversationViewController *conversationViewController = [[LCCKConversationViewController alloc] initWithConversationId:conversationId]; 
[self.navigationController pushViewController:viewController animated:YES];

 ```

**Comment by ChenYilong** [comment]
复现Demo：https://github.com/jwfing/FreeChat

**Comment by ChenYilong** [comment]
这个不是ChatKit的问题，是这个Demo的问题。修改方法：将 storyboard中原有的以下结构：

navigation bar -> tabbar -> 四个ViewController

改为

tabbar --> 四个navigation bar -->四个ViewController

**Comment by ChenYilong** [comment]
v0.6.0版本已经发布，修复了该问题。相关issue： https://github.com/leancloud/ChatKit-OC/issues/30#issuecomment-240942817

**Comment by ChenYilong** [comment]
已修复
