### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by zzgo** [leancloud/ChatKit-OC#144]
## Base Info for this issue 

 1. ChatKit Version：0.7.17
 2. App-ID: 
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

如何 国际化 表情包的输入?

![](http://of8uz9wjk.bkt.clouddn.com/WechatIMG1.jpeg)

如上图输入框中显示，因为我们应用主要针对国外用户，显示中文的话就不太好。希望可以国际化表情输入。

## 2. Please help me in this way.

使用表情输入时，名称国际化（其实我觉得支持英文就都可以了）

**Comment by ChenYilong** [comment]
这个是原生就支持的，你只需要自定义下表情包所在的bundle，将里面的plist文件改成英文的，就可以了。详见自定义样式文档：https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit%20自定义样式.md#自定义-bundle-命名规则

**Comment by zzgo** [comment]
我有尝试按照 [命名规则](https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit%20自定义样式.md#自定义-bundle-命名规则) 的方法去做国际化，拷贝下来bundle -> 修改名称 ->  拖入工程，但是不生效。

该检查哪些地方确保我的设置生效？

**Comment by ChenYilong** [comment]
这个会有编译缓存，清理缓存重试。

**Comment by zzgo** [comment]
我进入 `~/Library/Developer/Xcode/DerivedData` ，删除了底下的文件，但是还是一样的效果。是不是要把原来的bundle要删掉？

**Comment by ChenYilong** [comment]
不用删原来的bundle，还是你的编译缓存没清理掉，删缓存、Clean。

**Comment by ChenYilong** [comment]
可以试着改下其他的国际化文件做下验证。

**Comment by zzgo** [comment]
直接改了是可以生效。但是拷贝下来丢进去，真的木有用啊，删除了缓存，clean了工程，然后还删除了已经安装的app。

我的是0.7.19版本，用pod引入的。

**Comment by zzgo** [comment]
这是一个Bug，已修复，这里的讨论： #146

**Comment by ChenYilong** [comment]
CocoaPods 已经更新到V0.7.21，请更新

**Comment by ChenYilong** [comment]
文档已更新，之前文档的命名规则有问题：https://github.com/leancloud/ChatKit-OC/issues/223
