### ISSUE TITLE
关于获取未读消息数量问题

### ISSUE THREAD

**Issue by bestmmmz** [leancloud/ChatKit-OC#149]
**出现该问题描述**
我的App需求是LCCKConversationListViewController放到第三个tabbar上.当程序运行起来,setMarkBadgeWithTotalUnreadCountBlock不执行,在首页面无法获取出去未读消息数量, tabbar上没有badge提示.
**自己的解决办法**
我自己的解决办法是初始化LCCKConversationListViewController时调用refresh方法, 让其调用setMarkBadgeWithTotalUnreadCountBlock:来获取未读消息数量,进行手动设置, 需求是实现了.
但是现在出现的问题是调用refresh方法会创建tableview,也就是当你点击第三个tabbar的时候, VC上有两个tableview, 交互无法进行.
**希望龙哥可以提供一个API来获取未读消息数量,我来手动设置badge**

**Comment by ChenYilong** [comment]
这个能解决你的需求吗？Reference：https://github.com/leancloud/ChatKit-OC/issues/77

**Comment by bestmmmz** [comment]
意思就是我获取本地的未读消息数量, 再获取leancloud的未读消息数量, 累加一起,设置badge. 对吧

**Comment by ChenYilong** [comment]
这个方法获取的未读数，已经包含了：LeanCloud的未读消息消息数量。

**Comment by bestmmmz** [comment]
已经解决. 感谢
还有大家使用[[LCCKConversationListService sharedInstance] findRecentConversationsWithBlock:^(NSArray *conversations, NSInteger totalUnreadCount, NSError *error)获取未读消息时, 要在openWithClientId方法  success之后调用, 要不获取不到conversations和totalUnreadCount
