### ISSUE TITLE
最近消息列表,cell右滑UITableViewRowAction显示不完整.

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#161]
![image](https://cloud.githubusercontent.com/assets/12640162/19917630/cd7d5f2c-a0ff-11e6-8c73-cf25e9284378.png)

如图.

 1. ChatKit Version：0.8.0
 2. Language：Swift
 3. iOS System Version：iOS10
 4. Prototype（是否是真机）：YES

**Comment by ChenYilong** [comment]
请问你的Pod里是否集成了CYLTableViewRowAction，

推测你应该没有集成CYLTableViewRowAction，

请检查你的国际化文件中“删除”这个字段是否正确设置，怀疑你的“删除”字段显示成了空字符串。

另外这个是显示不完整，还是说长度就只有这么长？拖拽能看到剩余的部分吗？

**Comment by Seppuu** [comment]
a,没有集成CYLTableViewRowAction
b,在CustomizedChatKitOther中"Delete" = "删除";
c,是显示不完整,长度只有这么长.

**Comment by ChenYilong** [comment]
> c,是显示不完整,长度只有这么长.

 是红色部分只有图片中显示的这么长吗？再拖拽的话，也看不到红色的部分了吧。

那应该就是国际化的问题

请尝试将配置中的 `LCCKLocalizedStrings(@"Delete")` 改为  `@"删除"` 试试，看下效果。

**Comment by Seppuu** [comment]
LCCKLocalizedStrings(@"Delete") 改为 @"删除" 就OK了.

**Comment by ChenYilong** [comment]
ChatKit版本号发来，0.7.21修复过一个本地化的问题，

见： https://github.com/leancloud/ChatKit-OC/issues/146

**Comment by Seppuu** [comment]
v0.8.0,但是从GitHub上下载的demo没有这个问题.

**Comment by ChenYilong** [comment]
嗯，我测试下，你也清理下缓存，看是不是编译缓存的问题。国际化编译缓存也会有影响。

**Comment by ChenYilong** [comment]
文档已更新，之前文档的命名规则有问题：https://github.com/leancloud/ChatKit-OC/issues/223

**Comment by ChenYilong** [comment]
请问显示不全的问题解决没有，解决的话issue关闭了，有问题的话，再重新打开吧。

**Comment by Seppuu** [comment]
修改了自定义bundle之后问题解决了.

**Comment by ChenYilong** [comment]
你的应用上线没，叫什么名字

**Comment by Seppuu** [comment]
闲惠企业版

**Comment by ChenYilong** [comment]
加下微信 chenyilong1010

**Comment by Seppuu** [comment]
以前加过.有什么事吗?
