### ISSUE TITLE
如何根据clientId来获取用户信息？

### ISSUE THREAD

**Issue by mikumaycry** [leancloud/ChatKit-OC#17]
chatKit中需要设置fetchProfilesBlock，通过userId（即clientId）来获取用户信息，生成实现了LCCKUserDelegate协议对象，提供给系统使用。根据clientId来获取用户信息的接口需要自己实现吗？还是leancloud已经支持了？

**Comment by ChenYilong** [comment]
需要自己去实现，这个接口设计的目的，是为了让 App 接入自己已有的用户系统，比如你可以把App里用户系统的UserId作为ChatKit里的ClientId，但是你自己的用户系统，ChatKit是无法通过App里的API去获得头像、昵称都信息的。所以就设计了这个接口：让接入方告知下，我如何通过userId去获知头像、昵称等信息。

当然也可以使用LeanCLoud自带的用户系统AVUser，但是也需要实现fetchProfilesBlock接口，代码如下：


 ```
    [[LCChatKit sharedInstance] setFetchProfilesBlock:^(NSArray<NSString *> *userIds, LCCKFetchProfilesCallBack callback) {
        NSMutableArray<id<LCCKUserModelDelegate>> *userList = [NSMutableArray array];
        for (NSString *userId in userIds) {
            //MyUser is a subclass of AVUser, conforming to the LCCKUserModelDelegate protocol.
            AVQuery *query = [LCCKUser query];
            NSError *error = nil;
            LCCKUser *object = (LCCKUser *)[query getObjectWithId:userId error:&error];
            if (error == nil) {
                [userList addObject:object];
            } else {
                if (callback) {
                    callback(nil, error);
                    return;
                }
            }
        }
        if (callback) {
            callback(userList, nil);
        }
    }
     ];

  ```

**Comment by mikumaycry** [comment]
但是由于是接入已有的系统，目前用户信息存储在conversation的attr中，可以在App中由userId获取到clientId，目前有两种想法
1.在联网查询conversation时，提取clientId和相关用户信息，以clientId为主键存储到数据库中，然后在FetchProfilesBlock中根据useId检索数据库，获取用户信息；
2.在FetchProfilesBlock中由userId随机拖取一个conversation，从conversation中获取用户信息，同样存储到数据库。
我比较倾向于第一个方案，但不清楚FetchProfilesBlock是否可能会在获取到conversation前被调用。

**Comment by ChenYilong** [comment]
这样是不可行的，FetchProfilesBlock 必须在 openWithClientId 前设置好.

从描述里可以知道，你们有自己的用户系统，那么你们一定有这样的API：

根据 userId 获知 User的相关信息。

那么你现在如果想使用ChatKit，那么你就需要放弃使用之前借助 attr 信息来获知用户信息的方案。ChatKit 在需要使用用户信息时只会去  `FetchProfilesBlock` 这个方法里去索取。


将APP已有用户系统提供给 ChatKit 的代码实现：

 ```Objective-C
[[LCChatKit sharedInstance] setFetchProfilesBlock:^(NSArray<NSString *> *userIds, LCCKFetchProfilesCallBack callback) {
        if (userIds.count == 0) {
            NSInteger code = 0;
            NSString *errorReasonText = @"User ids is nil";
            NSDictionary *errorInfo = @{
                                        @"code":@(code),
                                        NSLocalizedDescriptionKey : errorReasonText,
                                        };
            NSError *error = [NSError errorWithDomain:@"LCChatKit"
                                                 code:code
                                             userInfo:errorInfo];
            !callback ?: callback(nil, error);
            return;
        }
        
        NSMutableArray *users = [NSMutableArray arrayWithCapacity:userIds.count];
        //注意：这个For循环模拟了 通过 userIds 同步查询 user信息的过程，这里需要替换为App的API同步查询
        for (NSDictionary *user in LCCKContactProfiles) {
            if ([userIds containsObject:user[LCCKProfileKeyPeerId]]) {
                NSURL *avatarURL = [NSURL URLWithString:user[LCCKProfileKeyAvatarURL]];
                LCCKUser *user_ = [[LCCKUser alloc] initWithUserId:user[LCCKProfileKeyPeerId] name:user[LCCKProfileKeyName] avatarURL:avatarURL];
                [users addObject:user_];
            }
        }
        !callback ?: callback([users copy], nil);
    }];

 ```

**Comment by ChenYilong** [comment]
这里阐述下 ClientId 与 UserId 的关系：

 ChatKit 与服务端进行数据交互时只会使用 ClientId，但界面展示则需要用到 App 已有用户系统的 User 信息，这时候 ChatKit 就会回调 `FetchProfilesBlock` 来获取用户信息，当然主要是获取 头像和用户名。

比如上面的代码中 userIds 这个就是 ClientIds，但 LCCKProfileKeyPeerId 这个就是 App 已有用户系统的UserId。除了LCCKUserDelegate中的userId，其余在 ChatKit 接口中定义所有的 UserId 均是 ClientId，建议将 App 已有的用户系统中的 UserId 直接设置为 ClientId，如果 UserId 与 ClientId 不相等，那么就需要在上面的 `-setFetchProfilesBlock:` 方法中添加 clientIds 转换为 userIds 的步骤，然后再拿 userIds 去调用 App 已有的 API 来进行查询。

**Comment by mikumaycry** [comment]
明白了，感谢你的耐心回答。

**Comment by ChenYilong** [comment]
问下你们的ClientId是如何设计的？是不是与已有App的UserId不一致？

**Comment by mikumaycry** [comment]
不一样，目前有根据App的userId请求clientId的接口，以及根据conversationId请求对话相关信息的接口，此外的用户数据都放在了attr中，目前只能先缓存对话，再从对话中查询用户信息了

**Comment by ChenYilong** [comment]
`-setFetchProfilesBlock:` 这是上层提供用户信息的Block，由于 ChatKit 并不关心业务逻辑信息，比如用户昵称，用户头像等。用户可以通过 ChatKit 单例向 ChatKit 注入一个用户信息内容提供Block，通过这个用户信息提供Block，ChatKit 才能够正确的进行业务逻辑数据的绘制。

**Comment by mickymickymicky** [comment]
@ChenYilong 

请问下 上面对接avuser系统的代码 有几个地方看不懂 
        NSMutableArray<id<LCCKUserDelegate>> *userList = [NSMutableArray array];
            AVQuery *query = [LCCKUser query];
            NSError *error = nil;
            LCCKUser *object = (LCCKUser *)[query getObjectWithId:userId error:&error];

不知道换成swift该怎么写？
或者能不能麻烦帮忙转换一下 很感谢

**Comment by ChenYilong** [comment]
文档已经完善

**Comment by ChenYilong** [comment]
类似：

 ```Objective-C
LCChatKit.sharedInstance().fetchProfilesBlock = {(_ userIds, _ completionHandler) -> Void in
            var users = [LCCKUserDelegate]()
            let query = AVQuery(className: "_User")
            for (index, userId) in (userIds?.enumerated())! {
                    let avuser = query.getObjectWithId(userId)
                let user_ = LCCKUser(userId: userId, name: avuser?.object(forKey: "customUserName") as! String!, avatarURL: NSURL(string: (avuser?.value(forKey: "avatar") as! AVFile).url!) as! URL, clientId: userId)
                users.append(user_!)
            }
            completionHandler!(users, nil)
        }
 ```

**Comment by ChenYilong** [comment]
这个issue也有对于这几个概念的理解：https://github.com/leancloud/ChatKit-OC/issues/17
