### ISSUE TITLE
录音时可以点击其它控件，导致bug

### ISSUE THREAD

**Issue by yyl1989726** [leancloud/ChatKit-OC#177]
录音的时候，将控件 LCCKProgressHUD，加在self.overlayWindow上面？是有什么原因吗？ 这样会导致一个问题，就是在录音过程中，可以通过另一只手操作界面的其它控件，比如返回，返回后就会出现下图所示。如果直接将LCCKProgressHUD加在[UIApplication sharedApplication].keyWindow上面就不会有这个情况；
![c5d608b5274119b3e10b836f130881ae](https://cloud.githubusercontent.com/assets/8705722/20342919/61a1b964-ac27-11e6-9b65-41d7fecebbdf.jpg)

**Comment by ChenYilong** [comment]
fixed，v0.8.3已发布。
