### ISSUE TITLE
输入框在IOS 10中换行会有偏移

### ISSUE THREAD

**Issue by yyl1989726** [leancloud/ChatKit-OC#178]
现在的版本，在IOS10输入换行的时候，textView的内容向上便宜，再下次输入后恢复正常，原因是高度变化后，textView更新约束，重新设置了contentOffset；我是在设置contentOffset做了0.01秒的延迟，发现能解决这个问题；
![94310686-3a93-4d6e-87b9-4d4223e4ccd1](https://cloud.githubusercontent.com/assets/8705722/20343071/f85058e8-ac27-11e6-8050-47064058b28f.png)
![fef8e207-70a5-4705-b951-61c3ed052561](https://cloud.githubusercontent.com/assets/8705722/20343073/f99df084-ac27-11e6-8fcc-0de79e001151.png)
![c43456b0-7a12-4b0b-b0c1-0dc6c9fd1930](https://cloud.githubusercontent.com/assets/8705722/20343077/fb487878-ac27-11e6-833f-c747dbfa993a.png)

**Comment by ChenYilong** [comment]
fixed，v0.8.2已发布。

**Comment by ChenYilong** [comment]
另外发现iOS9下粘贴一段文字也会发生类似的问题，这个方法也能解决，修改下，不做版本检测了。
