### ISSUE TITLE
红包点击发送，提示登录信息失效了

### ISSUE THREAD

**Issue by BoyLiJiaWei** [leancloud/ChatKit-OC#179]
## Base Info for this issue 

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
@DylanDu123

**Comment by BoyLiJiaWei** [comment]
都没人回复一下吗

**Comment by ChenYilong** [comment]
https://github.com/leancloud/ChatKit-OC/pull/184

**Comment by ChenYilong** [comment]
@DylanDu123 说：目前针对当前线上解决了这个问题，这周我们会发个新版本，到时候再重新修改。

**Comment by BoyLiJiaWei** [comment]
好

**Comment by ChenYilong** [comment]
@DylanDu123 请在发版本后告知下，我更新下ChatKit的版本号，

**Comment by DylanDu123** [comment]
好的，正在修改中

**Comment by ChenYilong** [comment]
fixed: https://github.com/leancloud/ChatKit-OC/pull/192

**Comment by ChenYilong** [comment]
双击一个过期红包，第一次弹框提示过期，第二次crash：

 ```Objective-C
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '入参meeageModel中接收者昵称 meeageModel.redpacketReceiver.userNickname为空'
 ```

@DylanDu123

**Comment by DylanDu123** [comment]
此问题是手动抛出异常。release不会造成Crash
异常原因reason: '入参meeageModel中接收者昵称 meeageModel.redpacketReceiver.userNickname为空'
校验位置在RedpacketMessageCell line:142
现已更新新版本SDK。去掉非必要的参数校验。

**Comment by ChenYilong** [comment]
已经Merge
