### ISSUE TITLE
目前 ChatKit 是否支持语音通话 和视频通话，像QQ 那样的，如果不行，那最新的LiveKit可以做到吗？

### ISSUE THREAD

**Issue by hbxn740150254** [leancloud/ChatKit-OC#187]
## Base Info for this issue 
目前 ChatKit 是否支持语音通话 和视频通话，像QQ 那样的，如果不行，那最新的LiveKit可以做到吗？

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
这个都还不支持。LiveKit是做直播的，视频通话还不支持。

**Comment by ChenYilong** [comment]
统一在  https://github.com/leancloud/ChatKit-OC/issues/128 回复
