### ISSUE TITLE
LCCKChatBar的自动布局约束问题

### ISSUE THREAD

**Issue by mikumaycry** [leancloud/ChatKit-OC#19]
2016-07-13 20:16:09.237 ChatKit-OC[20963:350320] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(
	    "<MASLayoutConstraint:0x7afbd970 UIButton:0x7ae3f470.left == UIView:0x7c645500.left + 10>",
	    "<MASLayoutConstraint:0x7af6d2d0 UIButton:0x7c640930.right == UIView:0x7c645500.right - 10>",
	    "<MASLayoutConstraint:0x7c7767c0 UIButton:0x7af191a0.right == UIButton:0x7c640930.left - 10>",
	    "<MASLayoutConstraint:0x7afbb120 UITextView:0x7da44e00.left == UIButton:0x7ae3f470.right + 10>",
	    "<MASLayoutConstraint:0x7c772ce0 UITextView:0x7da44e00.right == UIButton:0x7af191a0.left - 10>",
	    "<MASLayoutConstraint:0x7af41b60 UIView:0x7c645500.left == LCCKChatBar:0x7c6c73a0.left>",
	    "<MASLayoutConstraint:0x7af0fc30 UIView:0x7c645500.right == LCCKChatBar:0x7c6c73a0.right>",
	    "<NSLayoutConstraint:0x7af433b0 LCCKChatBar:0x7c6c73a0.width == 0>"
	)
	
	Will attempt to recover by breaking constraint 
	<MASLayoutConstraint:0x7afbb120 UITextView:0x7da44e00.left == UIButton:0x7ae3f470.right + 10>

在进入聊天界面后，会出现大量的Unable to simultaneously satisfy constraints提示，主要都是关于LCCKChatBar中的布局问题，应该怎样定位和修改这些布局错误？

**Comment by ChenYilong** [comment]
ChatKit 会在稍后的版本中移除这些错误。

**Comment by ChenYilong** [comment]
v0.3.8 已经移除，https://github.com/leancloud/ChatKit-OC/commit/b9a772bc3a636200fef1171b2c0ca286f8c0dae8
