### ISSUE TITLE
键盘的 LCCKChatMoreView 问题

### ISSUE THREAD

**Issue by xueqiulou** [leancloud/ChatKit-OC#209]
## Base Info for this issue 

!

点击聊天键盘的+号按钮, LCCKChatMoreView [上边并没有拍照,图片等items,@ChenYiLong需要用户自己设置吗?

[2016-12-07 16 20 26](https://cloud.githubus)ercontent7.17m/assets/13198448/20960127/ca155eec-bc99-11e6-883a-e86b3f709cfc.png)

 1. ChatKit Version：0.8.5
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
对，需要设置，你看下Demo里的做法：

`+ (void)invokeThisMethodInDidFinishLaunching`
