### ISSUE TITLE
ChatKit有没有关闭消息声音的函数

### ISSUE THREAD

**Issue by sunlei053667** [leancloud/ChatKit-OC#213]
## Base Info for this issue 

提问: ChatKit有没有关闭消息声音的函数

 1. ChatKit Version：0.8.0
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
有，开关在：ChatKit-Settings.plist

**Comment by sunlei053667** [comment]
看到了，ios8开始已经不允许全局控制音量了，只能在播放的时候控制声音。我的理解对不对？
ChatKit-Settings.plist内容是：
{
    Conversation =     {
        needPlaySoundWhenChatting = 1;
        needPlaySoundWhenNotChatting = 1;
        needVibrateWhenNotChatting = 1;
    };
}

**Comment by ChenYilong** [comment]
我这个开关不是控制系统的声音，是在ChatKit里的逻辑：

接收消息的时候，我看下这个开关，再决定是否调用play声音的方法。
