### ISSUE TITLE
红包 SDK 升级到 3.3.1 还是无法使用

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/ChatKit-OC#214]
![image](https://cloud.githubusercontent.com/assets/6046086/20997270/f654b58e-bd3e-11e6-85e3-5840c5284912.png)

**Comment by ChenYilong** [comment]
@DylanDu123

**Comment by DylanDu123** [comment]
1.此问题为偶发。一般为网络出错。造成不能同步token问题。使用最新版本LeanCloud一定程度上修复了此问题。

**Comment by BoyLiJiaWei** [comment]
之前就出现这个问题，更新到3.3.1还是有这个问题

**Comment by ChenYilong** [comment]
@DylanDu123

**Comment by BoyLiJiaWei** [comment]
还是这个问题啊，怎么解决，基本上跟chatkit里面写的一样

**Comment by BoyLiJiaWei** [comment]
@ChenYilong @DylanDu123

**Comment by BoyLiJiaWei** [comment]
@BinaryHB

**Comment by BoyLiJiaWei** [comment]
红包充值就可以，为什么发红包就发不出去啊

**Comment by ChenYilong** [comment]
@DylanDu123

**Comment by ChenYilong** [comment]
你打版本号是多少？

**Comment by DylanDu123** [comment]
目前版本是3.4.0

**Comment by BoyLiJiaWei** [comment]
现在是我都不知道是哪里的问题，可以聊天，红包可以充钱，但是发送的时候提示登录验证失败，是什么鬼

**Comment by DylanDu123** [comment]
这里不方便 可以私聊 QQ 472624215

**Comment by ChenYilong** [comment]
已解决
