### ISSUE TITLE
关于系统消息&广播消息name为null的问题

### ISSUE THREAD

**Issue by bestmmmz** [leancloud/ChatKit-OC#215]
restAPI发送的系统消息和广播消息from peerId为空, 最近会话列表name为null.
希望chatkit可以进行判断, from peerId为空时候, 不显示name.
并且from peerId为空时, 进入聊天页面会crash, 崩溃到UITableView+FDTemplateLayoutCell框架
崩溃信息:
![image](https://cloud.githubusercontent.com/assets/18080128/21078264/78a5ae60-bfa3-11e6-80d8-c89bbe1d5f16.png)

还有参考这个issue #54 ,增加了群组聊天是否显示name的开关, 但是我并没有找到这个开关, 希望龙哥指点一下

**Comment by ChenYilong** [comment]
贴下系统消息的发送代码

**Comment by bestmmmz** [comment]
![image](https://cloud.githubusercontent.com/assets/18080128/21098012/39a7d760-c0a2-11e6-82af-b6a56b150575.png)
这是系统消息代码

**Comment by ChenYilong** [comment]
这种情况在ChatKit里已经处理了，如果发现昵称是nil的话，就不显示。

具体的处理是在 LCCKLastMessageTypeManager 这个类中

 ```Objective-C
+ (NSAttributedString *)attributedStringWithMessage:(AVIMTypedMessage *)message conversation:(AVIMConversation *)conversation userName:(NSString *)userName {
    NSString *title = [self getMessageTitle:message];
    if (conversation.lcck_type == LCCKConversationTypeGroup) {
        if (!userName) {
            userName = @"";
        } else {
            userName = [NSString stringWithFormat:@"%@: ", userName];
        }
        title = [NSString stringWithFormat:@"%@%@", userName, title];
    }
 ```


这里可能出现问题的原因是，你的setFetchProfilesBlock设置时的逻辑问题：如果去自己服务端查询1a对应的user信息时，如果查不到应该返回一个name字段为nil的user对象。推测可能，你的name字段不为nil，可能是个[NSNull null]对象。

**Comment by bestmmmz** [comment]
好的, 我知道原因了...

**Comment by ChenYilong** [comment]
请问问题出在哪里？

**Comment by bestmmmz** [comment]
我们这个是不需要1a的这个clientId的, 1a这个用户在我们自己的user用户体系中是没有的.
所以应该clientid置空就可以解决

**Comment by ChenYilong** [comment]
更保险的做法是：保留from_peer这个值1a，然后在setFetchProfilesBlock中，如果发现服务端查不到，就返回一个name字段为空，clientId字段有值的user对象。可以这样初始化，仅仅使用clientId初始化，`LCCKUser *user = [LCCKUser userWithClientId:clientId];`这样也可以解决点击进去系统对话页面就crash的问题。

**Comment by bestmmmz** [comment]
好的, 明白 我去增加以下此容错方法.

**Comment by bestmmmz** [comment]
还是有问题
按我的方法来做服务器那边clientId不可以置空, leancloud不允许
按你的方法来做, LCCKUser *user = [LCCKUser userWithClientId:clientId]仅仅初始化clientId,用户名不显示了.但是会显示clientId.

**Comment by ChenYilong** [comment]
`-invokeThisMethodInDidFinishLaunching`方法里加一行代码：

`[LCChatKit sharedInstance].isDisablePreviewUserId = YES;`

**Comment by ChenYilong** [comment]
请问是否解决了？解决的话，issue就关闭了。有问题的话，issue再打开吧。
