### ISSUE TITLE
[AVIMTextMessage sendMessage:]发送完消息,没有在消息列表中显示问题

### ISSUE THREAD

**Issue by DeanLee911** [leancloud/ChatKit-OC#217]
ChatKit Version：0.8.7
App-ID: XX
Language：Objective-C
iOS System Version：iOS10
Prototype（是否是真机）：YES
Issue Type：Q-A

self.client = [[AVIMClient alloc] initWithClientId:[TVMUserModel sharedInstance].tvmid];
[self.client openWithCallback:^(BOOL succeeded, NSError *error) {
[self.client createConversationWithName:@"我通过了你的好友验证请求,现在我们可以开始聊天了" clientIds:@[tvmid] attributes:nil options:AVIMConversationOptionUnique callback:^(AVIMConversation * _Nullable conversation, NSError * _Nullable error) {
            AVIMTextMessage* m = [AVIMTextMessage messageWithText:@"" attributes:nil];
            [conversation sendMessage:m callback:^(BOOL succeeded, NSError *error) {
                if (succeeded) {
                    NSLog(@"发送成功！");
                }
            }];
        }];
    }];
[AVIMTextMessage sendMessage:]发送完消息,没有在消息列表中显示问题,

**Comment by ChenYilong** [comment]
```Objective-C
                      [[LCChatKit sharedInstance] insertRecentConversation:conversation];
 ```

参考在下面这个方法的中的使用：


 ```Objective-C
+ (void)lcck_exampleChangeGroupAvatarURLsForConversationId:(NSString *)conversationId
                                              shouldInsert:(BOOL)shouldInsert {
 ```
