### ISSUE TITLE
cocoapod导入，Masonry.h file not found问题 (Swift3.0，ChatKit版本0.8.7)

### ISSUE THREAD

**Issue by hanorz** [leancloud/ChatKit-OC#219]
## Base Info for this issue 

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 4. Here is my Debug log

如图#import "Masonry.h" 要改成#import <Masonry/Masonry.h>才能被找到
![f28e1e2a-a5ea-459a-a157-2967d326e330](https://cloud.githubusercontent.com/assets/9412189/21131689/0ed89426-c14b-11e6-99c1-c807049d0ccf.png)

![1702cf1c-57e4-4200-a379-83258390438c](https://cloud.githubusercontent.com/assets/9412189/21131692/15fc04f4-c14b-11e6-9884-57b8943ce44c.png)

**Comment by ChenYilong** [comment]
你的ChatKit版本过低，而且并不是0.8.7，任意文件的第五行都标注有ChatKit的版本号。请升级下你的版本。
