### ISSUE TITLE
关于peerId、clientId、userId、objectId到底是代表啥玩意的理解

### ISSUE THREAD

**Issue by Hitooo** [leancloud/ChatKit-OC#220]
## 关于用户的peerId、clientId、userId、objectId到底是代表啥玩意的理解

**下面来说一下我的理解，并且我也是这样做的：**

 1.大家在集成chatkit之前，肯定已经有了自己的一套用户体系，这套体系中基本都会包含userid这个字段来表示用户主键（比如张三的userid是zhangsan，系统管理员的userid是SYS），这个字段必须得对应到leancloud中的User表某一个字段；我是把它对应到User表中的username字段来用的，充当外键的作用；为了方便以后通过我们自己的用户体系中的userid找到这个AVUser对象。

 2. chatkit里面所有方法中需要传peeId或者clientId或者userId的地方，其实都是需要传用户的objectId。

 3. 你自己用户体系中UserModel需要实现LCCKUserDelegate的代理：

- userId：你自己用户体系中用户的主键

- name：你自己用户体系中用户的姓名

- avatarURL：LeanCloud中用户的头像

- clientId：LeanCloud中User表中用户的主键，即objectId。
4.我集成chatkit时产生的一些建议：

- App启动的时候，一次性去LeanCloud服务器把User表中所有用户拉取下来：
` AVQuery * query = [AVUser query];
    query.cachePolicy = kAVCachePolicyIgnoreCache;
    query.limit = 1000;
    [query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
          //把objects转化成存储自己的已经实现LCCKUserDelegate 的UserModel的数组usersArr后然后扔到缓存里
          [[LCCKUserSystemService sharedInstance] cacheUsers: usersArr];     
    }];
`

- 实现setFetchProfilesBlock，设置这个block的意思就是说你的本地缓存中没有完全匹配调用方想要的用户对象数组userIds，所以把整个userIds扔到这个block里，让你把那些没有缓存的用户去联网请求回来：
`AVQuery * query = [AVUser query];
    [query whereKey:@"username" equalTo:userid];
    AVUser *user = [query getFirstObject];
  //拿到LeanCloud的user之后存起来就完事了
`

**Comment by ChenYilong** [comment]
放这里讨论 https://github.com/leancloud/ChatKit-OC/issues/17
