### ISSUE TITLE
自定义bundle无法加载

### ISSUE THREAD

**Issue by Shvier** [leancloud/ChatKit-OC#223]
## Base Info for this issue 

 1. ChatKit Version：v0.8.5
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
你自定义了哪个bundle？

**Comment by Shvier** [comment]
文档中的命名规范是"CustomizedChatKit%@.bundle"，代码里的判断是"CustomizedChatKit.%@.bundle"，修改文档或者修改代码：
// NSBundle+LCCKExtension.m
NSString *customizedBundlePathComponent = [NSString stringWithFormat:@"CustomizedChatKit.%@.bundle", bundleName];

**Comment by Shvier** [comment]
https://github.com/leancloud/ChatKit-OC/blob/49a3bd2cd5ecd84d15db17e2eb9770f373b59429/ChatKit/Class/Tool/Categories/NSBundle%2BLCCKExtension.m#L20

**Comment by ChenYilong** [comment]
多谢提醒，会修改下文档。
