### ISSUE TITLE
表情排版行数

### ISSUE THREAD

**Issue by Shvier** [leancloud/ChatKit-OC#225]
## Base Info for this issue 

 1. ChatKit Version：0.8.5
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

表情排版行数

## 2. Please help me in this way.

https://github.com/leancloud/ChatKit-OC/blob/49a3bd2cd5ecd84d15db17e2eb9770f373b59429/ChatKit/Class/Module/Conversation/View/ChatBar/LCCKChatFaceView.m#L158

应该是`self.maxRows =  height > 480 ? 4 : 3;`吧？

**Comment by ChenYilong** [comment]
不是，你运行看下效果。

**Comment by ChenYilong** [comment]
欢迎提PR
