### ISSUE TITLE
聊天页面被挡到了

### ISSUE THREAD

**Issue by BoyLiJiaWei** [leancloud/ChatKit-OC#226]
## Base Info for this issue 

    v0.8.5

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

集成chatkit 聊天页面用自己的导航栏  挡到聊天消息了

**Comment by ChenYilong** [comment]
请帖下你是如何自定义导航栏的。

**Comment by BoyLiJiaWei** [comment]
说错了 因为控制器是继承LCCKConversationViewController
所以我就在上面直接加了一个view

UIView *naviV = [[UIView alloc] initWithFrame:CGRectMake(0, 0, ScreenWidth, 64)];
    naviV.backgroundColor = mainColor;
    [self.view addSubview:naviV];
    
    UILabel *_titleLable = [[UILabel alloc]initWithFrame:CGRectMake(40, 20, ScreenWidth-80, 44)];
    _titleLable.backgroundColor = [UIColor clearColor];
    _titleLable.textAlignment = NSTextAlignmentCenter;
    _titleLable.font = FontSet(17);;
    _titleLable.textColor = [UIColor whiteColor];
    _titleLable.text = @"聊天";
    [naviV addSubview:_titleLable];
    
    UIButton * _backBtn = [UIButton buttonWithType:UIButtonTypeCustom];
    _backBtn.frame = CGRectMake(0, 19, 50, 44);
    [_backBtn setImage:[UIImage imageNamed:@"返回.png"] forState:UIControlStateNormal];
    [_backBtn setImageEdgeInsets:UIEdgeInsetsMake(12, 14, 12, 24)];
    [_backBtn addTarget:self action:@selector(backAction:) forControlEvents:UIControlEventTouchUpInside];
    _backBtn.adjustsImageWhenHighlighted = NO;
    [naviV addSubview:_backBtn];

**Comment by BoyLiJiaWei** [comment]
这个要怎么修改？

**Comment by ChenYilong** [comment]
你这个`naviV` 这个View是怎么做到自定义导航栏的，代码贴下。

**Comment by BoyLiJiaWei** [comment]
我就直接添加上去当作导航栏的

**Comment by ChenYilong** [comment]
代码

**Comment by BoyLiJiaWei** [comment]
控制器是继承LCCKConversationViewController  代码就就是上面的代码  没有别的了

**Comment by ChenYilong** [comment]
这样自定义是不可行的。推荐你阅读下如何自定义navigationBar的相关博客，比如这篇。https://www.appcoda.com/customize-navigation-status-bar-ios-7/

**Comment by BoyLiJiaWei** [comment]
我直接在上面加一个uiview 作为导航 为什么不行？
项目中其他的控制器都是继承baseviewcontroller 在baseviewcontroller中我创建一个view作为导航，把系统导航隐藏掉，现在是聊天页面我要继承LCCKConversationViewController ，所以不能继承我自己的baseviewcontroller，所以不明白你说的为什么不行

**Comment by ChenYilong** [comment]
聊天页面无法获知他的父类中还有一个view，并且聊天页面的y坐标需要等于view的高度。你的view高度可能设置为了64，明天别人设置了44，聊天页面怎么判断？

**Comment by ChenYilong** [comment]
改变 `navigationBar` 的颜色，背景图片这样的需求很常见。系统的 `navigationBar` 就能自定义，直接创建一个 `UIView` 到 `self.view` 上。你必然要改变子试图的y坐标，得不偿失。

**Comment by BoyLiJiaWei** [comment]
嗯，知道了，谢谢

**Comment by ChenYilong** [comment]
请问问题解决没有，解决的话issue关闭了，有问题的话，再重新打开吧。
