### ISSUE TITLE
获取不到未读消息lcck_unreadCount

### ISSUE THREAD

**Issue by hanorz** [leancloud/ChatKit-OC#228]
## Base Info for this issue 

 1. ChatKit Version：0.8.7
 2. App-ID: XX
 3. Language：Swift
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 4. Here is my Debug log

获取Conversations列表，就算有未读消息， lcck_unreadCount依然为0，怎么解决？

**Comment by ChenYilong** [comment]
https://github.com/leancloud/ChatKit-OC/issues/149
