### ISSUE TITLE
pod安装失败

### ISSUE THREAD

**Issue by xingyinbuli** [leancloud/ChatKit-OC#230]
## Base Info for this issue 

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
详细描述下，pod失败具体报错是什么？

**Comment by ChenYilong** [comment]
没有具体pod错误提示，无法定位问题。测试下来，pod没问题。
