### ISSUE TITLE
pod error

### ISSUE THREAD

**Issue by hychen1024** [leancloud/ChatKit-OC#231]
## Base Info for this issue 

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 4. Here is my Debug log

ld: framework not found AVOSCloud
clang: error: linker command failed with exit code 1 (use -v to see invocation)

podfile中添加 pod 'ChatKit'  pod成功后运行，报错

**Comment by ChenYilong** [comment]
测试下来，pod 没问题。请问后来解决了吗？

**Comment by hychen1024** [comment]
已经解决~3q 导入框架太多警告了，用了inhibit_all_warnings!也没用 特别是哪个duplicate definition MJ和masonry

**Comment by ChenYilong** [comment]
ok
