### ISSUE TITLE
LCCKChatMoreView问题

### ISSUE THREAD

**Issue by Gavin001** [leancloud/ChatKit-OC#236]
## Base Info for this issue 

在我的项目中集成ChatKit，发现在聊天界面点击输入框的时候，会初始化LCCKChatMoreView的几个功能按钮（拍照，图片。。），模拟器上运行没有问题，但是真机上会崩溃。

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

崩溃位置在LCCKChatMoreView.m 的- (void)setupItems方法，[item fillWithPluginTitle:obj pluginIconImage:self.images[idx]];

**Comment by Gavin001** [comment]
@hhx2

**Comment by ChenYilong** [comment]
请检查你的几个插件的index是否连续，请查看文档：

https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit%20自定义业务.md#删除自定义插件自定义消息自定义-cell

**Comment by Gavin001** [comment]
我使用的默认的三个功能，没有做删除之类的操作，也会出现排序中断或者不连续的情况吗？

**Comment by ChenYilong** [comment]
ChatKit 版本多少？建议更新到最新版。

**Comment by Gavin001** [comment]
我现在用的是0.8.0，我更新一下先，谢谢！

**Comment by ChenYilong** [comment]
等等，0.8应该没有该问题，你确定是0.8.0吗？因为默认的几个插件，在新版本的demo中不止三个。你需要按照文档删除，才能减少到三个。

**Comment by Gavin001** [comment]
是0.8.0，我的cocoapods本地库最新的是0.8.0，self.titles里面只有三个元素“拍摄”，“照片”，“位置”，如果说是排序出了问题，那模拟器应该也会崩溃才对啊，所以很迷惑，找了很久原因没找到

**Comment by ChenYilong** [comment]
发个Demo给我，luohanchenyilong@163.com 。
