### ISSUE TITLE
后台切换到前台时，badge会乘以2

### ISSUE THREAD

**Issue by sunlei053667** [leancloud/ChatKit-OC#237]
## Base Info for this issue 

1、我的app不是tabbar类型的。所以，聊天界面不是一直都在的。
类似于下面这种形式去把聊天界面调出来。
navigationController.viewControllers = @[ChatListVC];
然后用navigationController.viewController= @[anotherVC];这种形式切换到其他的界面。

2、为了解决聊天界面一开始不存在导致无法获取message badge更新的问题，我在启动的时候就多加了一个函数，注册了observer，来刷新badge. 保证能够在程序一启动的时候就能够获取到消息badge的更新。
  [[NSNotificationCenter defaultCenter] addObserver:self 
selector:@selector(refreshMessageBadge) name:LCCKNotificationMessageReceived object:nil];

//refreshMessageBadge的大概逻辑如下
     

 ```Objective-C
    -(void) refreshMessageBadge{
       [[LCCKConversationListService sharedInstance] findRecentConversationsWithBlock:^(NSArray *conversations, NSInteger totalUnreadCount, NSError *error) {
            if (totalUnreadCount > 0) {
                NSString *badgeValue = [NSString stringWithFormat:@"%ld", (long)totalUnreadCount];
                if (totalUnreadCount > 99) {
                    badgeValue = LCCKBadgeTextForNumberGreaterThanLimit;
                }
                [MenuController setMessageBadgeNumber:totalUnreadCount];
                [[UIApplication sharedApplication] setApplicationIconBadgeNumber:totalUnreadCount];
            } else {
                [MenuController setMessageBadgeNumber:0];
                [[UIApplication sharedApplication] setApplicationIconBadgeNumber:0];
            }
        }];
}
 ```
3、此外我还配置了LCCChatKitExample+Setting.m中的设置badge函数。

 ```Objective-C
   - (void)lcck_exampleMarkBadgeWithTotalUnreadCount:(NSInteger)totalUnreadCount
                                       controller:(UIViewController *)controller {
    
    
    if (totalUnreadCount > 0) {
        NSString *badgeValue = [NSString stringWithFormat:@"%ld", (long)totalUnreadCount];
        if (totalUnreadCount > 99) {
            badgeValue = LCCKBadgeTextForNumberGreaterThanLimit;
        }
        [MenuController setMessageBadgeNumber:totalUnreadCount];
        [[UIApplication sharedApplication] setApplicationIconBadgeNumber:totalUnreadCount];
    } else {
        [MenuController setMessageBadgeNumber:0];
        MenuController * menuController = *******;
        [menuController reloadTableView];
        [[UIApplication sharedApplication] setApplicationIconBadgeNumber:0];
    }
}
 ```

 1. ChatKit Version：0.8.10
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

当我的app在前台的时候，发送消息都没有问题。只有当后台切换到前台的时候（并且在此期间收到消息）才会出现这个问题。
## 2. Please help me in this way.

提供一点debug思路

**Comment by sunlei053667** [comment]
还有一处会更新badgeNumber，每次程序启动的时候会调用下面的函数登陆ChatKit然后获取badge。但是这个是程序启动的时候才会调用，后台切换到前台没有用到这个地方。
+ (void)invokeThisMethodAfterLoginSuccessWithClientId:(NSString *)clientId
                                              success:(LCCKVoidBlock)success
                                               failed:(LCCKErrorBlock)failed {
    [[self sharedInstance] exampleInit];
    [[LCChatKit sharedInstance]
     openWithClientId:clientId
     callback:^(BOOL succeeded, NSError *error) {
         if (succeeded) {
             [self saveLocalClientInfo:clientId];
             [[LCCKConversationListService sharedInstance] findRecentConversationsWithBlock:^(NSArray *conversations, NSInteger totalUnreadCount, NSError *error)
             {
                 if (totalUnreadCount > 0) {
                     NSString *badgeValue = [NSString stringWithFormat:@"%ld", (long)totalUnreadCount];
                     if (totalUnreadCount > 99) {
                         badgeValue = LCCKBadgeTextForNumberGreaterThanLimit;
                     }
                  
                     [MenuController setMessageBadgeNumber:badgeValue.intValue];
                     [[UIApplication sharedApplication] setApplicationIconBadgeNumber:totalUnreadCount];
                 } else {
                    
                     [MenuController setMessageBadgeNumber:0];
                     [[UIApplication sharedApplication] setApplicationIconBadgeNumber:0];
                 }

                 NSLog(@"unread messages: %d", totalUnreadCount);
             }];
             !success ?: success();
         } else {
             [LCCKUtil showNotificationWithTitle:@"登陆失败"
                                        subtitle:nil
                                            type:LCCKMessageNotificationTypeError];
             !failed ?: failed(error);
         }
     }];
    // TODO:
}

**Comment by ChenYilong** [comment]
你的两个方法冲突了，refreshMessageBadge 未读数已经设置一遍了， 之后`setMarkBadgeWithTotalUnreadCountBlock`会在你未读数基础上累加，建议两个方法都先清零再设置。

**Comment by ChenYilong** [comment]
好的。
