### ISSUE TITLE
单词拼错。。。看着好难受

### ISSUE THREAD

**Issue by Maru-zhang** [leancloud/ChatKit-OC#241]
应该是fetchConversationWithPeerId而不是fecthConversationWithPeerId吧。。。

**Comment by ChenYilong** [comment]
的确是拼写错误，下个版本改过来。

**Comment by ChenYilong** [comment]
已经改好，会随下一版本发布。旧API废弃，新API会使用正确的拼写。再次感谢指正错误。

**Comment by Maru-zhang** [comment]
加油，希望ChatKit越来越好，有机会我也想参与其中

**Comment by ChenYilong** [comment]
多谢，新版本已经发布，已经修改。
