### ISSUE TITLE
请问一下第一次建立conversion 进入 conversion页面的时候，为什么用户会自动发一条Hello，这是系统默认的吗，可否取消

### ISSUE THREAD

**Issue by kooyear** [leancloud/ChatKit-OC#242]
## Base Info for this issue 

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
可以取消，issue里讨论过：https://github.com/leancloud/ChatKit-OC/issues/92
