### ISSUE TITLE
用户退出后，本地最近联系人会被清除，可以不让它们被清除吗？让下？次登入点时候还能看到最近联系人 列表，如何实现呢

### ISSUE THREAD

**Issue by kooyear** [leancloud/ChatKit-OC#243]
## Base Info for this issue 

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
这个问题讨论过，可以看下这个issue https://github.com/leancloud/ChatKit-OC/issues/94，最下面有结论，可以统一到该issue下讨论。
