### ISSUE TITLE
0.8.5 单点登录,点击强制登陆(再次登陆)Button之后,报错,应用崩溃.

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#247]
1. ChatKit Version：0.8.5
 3. Language：Objective-C ,Swift
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash
如题.
报错:-[LCCKConversationService setupSucceedMessageDatabaseWithPath:] [Line 212] database queue should not be nil !!!!

**Comment by ChenYilong** [comment]
误报，下版本删除掉。

**Comment by ChenYilong** [comment]
目前我发现了一个单点登录可能crash的原因是Demo层面的：


 ```Objective-C
+ (void)lcck_tryPresentViewControllerViewController:(UIViewController *)viewController {
    if (viewController) {
        UIViewController *rootViewController =
        [[UIApplication sharedApplication].delegate window].rootViewController;
        if ([rootViewController isKindOfClass:[UINavigationController class]]) {
            rootViewController =
            [(UINavigationController *)rootViewController visibleViewController];
        }
        [rootViewController presentViewController:viewController animated:YES completion:nil];
    }
}
 ```


这个方法中又一个地方不严谨，导致如果单点登录时如果，当前屏幕已经有一个presentViewController ，然后就会导致登录界面无法展示。


改成这样就好了。


 ```Objective-C
+ (void)lcck_tryPresentViewControllerViewController:(UIViewController *)viewController {
    if (viewController) {
        UIViewController *rootViewController =
        [[UIApplication sharedApplication].delegate window].rootViewController;
        if ([rootViewController isKindOfClass:[UINavigationController class]]) {
            rootViewController =
            [(UINavigationController *)rootViewController visibleViewController];
        }
        [rootViewController dismissViewControllerAnimated:NO completion:nil];
        [rootViewController presentViewController:viewController animated:YES completion:nil];
    }
}
 ```

**Comment by ChenYilong** [comment]
不知道你是不是这个问题。

**Comment by Seppuu** [comment]
应该不是这个问题,因为我重写了lcck_setupForceReconect方法.
崩溃时,最近一处相关代码是这里.
![image](https://cloud.githubusercontent.com/assets/12640162/21800680/adf95e72-d759-11e6-86fc-c9e5ed412cc4.png)

**Comment by ChenYilong** [comment]
被踢下线后，clientId的确会被抹去。你需要在调用 openClient时传入一个由你自己维护的clientId，不能依赖于ChatKit相关类保存的clientId，比如`[LCChatKit sharedInstance].clientId`，这个值会被抹掉。

**Comment by ChenYilong** [comment]
把你lcck_setupForceReconect的代码贴下

**Comment by Seppuu** [comment]
传入自己保存的clientId之后,正常了.

override func lcck_setupForceReconect() {
        
        LCChatKit.sharedInstance().forceReconnectSessionBlock = {

            (aError,granted,viewController,completionHandler) in
            
            //用户允许重连请求，发起重连或强制登录
            if (granted == true) {
                
                var force = false
                
                var title = "正在重连聊天服务..."
                
                if aError == nil {
                    
                }
                else {
                    
                    let isSingleSignOnOffline = (aError?._code == 4111)
                    
                    if (isSingleSignOnOffline) {
                        force = true
                        title = "正在强制登录..."
                    }

                }
                
                //get current viewController
                let appDelegate = UIApplication.shared.delegate as! AppDelegate
                
                let vc = appDelegate.window?.visibleViewController!
                
                NSObject.lcck_showMessage(title, to: vc!.view)
                
                //let clientId = LCChatKit.sharedInstance().clientId
                let currentClientId = Defaults.clientId.value!
                LCChatKit.sharedInstance().open(withClientId: currentClientId, force: force, callback: { (succeeded, error) in
                    
                    NSObject.lcck_hideHUD(for: vc!.view)
                    
                    completionHandler!(succeeded, error)
                })
                
                return
            }
            
            // 用户拒绝了重连请求,退回登录页面
            LCChatKitExample.lcck_clearLocalClientInfo()
            
            //显示引导以及登陆界面
            let appDelegate = UIApplication.shared.delegate as! AppDelegate
            
            appDelegate.showGuide()

            // - 显示返回信息
            let  code = 0
            let errorReasonText = "not granted"
            let errorInfo:[AnyHashable: Any] = [
                "code" : code,
                NSLocalizedDescriptionKey : errorReasonText
            ]
            
            let klass: AnyClass = object_getClass(self)
            
            let classString = NSStringFromClass(klass)
            let error = NSError(domain: classString, code: code, userInfo: errorInfo)
            
            completionHandler!(false, error)
 
        }
        
    }

**Comment by Seppuu** [comment]
出现了另一个问题.我用虚拟机和一台真机互踢.当其中一个终端第二次点击"确定"(强制重连)或者"取消"后, forceReconnectSessionBlock内代码都不会触发.alert弹窗消失.App此时是IM离线状态.
控制台此时没有日志输出.

**Comment by ChenYilong** [comment]
这个推测是Demo里的错误，请做如下修改 ：

之前在 `LCChatKitExample+Setting.h`中的



 ```Objective-C
+ (void)lcck_tryPresentViewControllerViewController:(UIViewController *)viewController {
    if (viewController) {
        UIViewController *rootViewController =
        [[UIApplication sharedApplication].delegate window].rootViewController;
        if ([rootViewController isKindOfClass:[UINavigationController class]]) {
            rootViewController =
            [(UINavigationController *)rootViewController visibleViewController];
        }
        [rootViewController presentViewController:viewController animated:YES completion:nil];
    }
}
 ```

改为：


 ```Objective-C
+ (void)lcck_tryPresentViewControllerViewController:(UIViewController *)viewController {
    if (viewController) {
        UIViewController *rootViewController =
        [[UIApplication sharedApplication].delegate window].rootViewController;
        if ([rootViewController isKindOfClass:[UINavigationController class]]) {
            rootViewController =
            [(UINavigationController *)rootViewController visibleViewController];
        }
        [rootViewController dismissViewControllerAnimated:NO completion:nil];
        [rootViewController presentViewController:viewController animated:YES completion:nil];
    }
}
 ```
