### ISSUE TITLE
怎么获取某消息体的已读状态

### ISSUE THREAD

**Issue by MrCoderMSH** [leancloud/ChatKit-OC#25]
我们现在有需求详细追踪到消息的送达、和已阅读状态，请问有没有这样的接口可以实现或者什么解决方案。谢谢

**Comment by ChenYilong** [comment]
送达现在原生支持的，SDK里的回调如下：


 ```Objective-C
/*!
 消息已投递给对方。
 @param conversation － 所属对话
 @param message - 具体的消息
 */
- (void)conversation:(AVIMConversation *)conversation messageDelivered:(AVIMMessage *)message;

 ```
这个我稍后加到ChatKit里，


已读未读状态，这个是我接下来要做的内容，现在还没有支持。

**Comment by MrCoderMSH** [comment]
ok,送达这个确实是有的，然后我看sdk的文档，貌似“暂态消息”这个概念可以解决类似的消息，但今天研究了一下  貌似暂态消息不能在聊天室外部去接收，是这样么？

**Comment by ChenYilong** [comment]
聊天室“外部”不知道怎么理解，暂态消息也可以在普通对话中接收，像普通消息一样，只要client是open状态都可以接收。

**Comment by MrCoderMSH** [comment]
聊天室外部是指不在具体某一聊天室内的时候，- (void)conversation:(AVIMConversation *)conversation didReceiveTypedMessage:(AVIMTypedMessage *)message  CDChatManager的这个方法没有收到暂态消息

**Comment by MrCoderMSH** [comment]
或者说能否给一个目前能够实现已读消息这样的实现思路，目前发现暂态消息不能够实现   因为暂态消息在用户离线时不能接受

**Comment by ChenYilong** [comment]
这个我们近期就会做，已经排期了。暂时没想到什么好的替代方法。

**Comment by ChenYilong** [comment]
Ref：https://github.com/leancloud/ChatKit-OC/issues/47

**Comment by ChenYilong** [comment]
统一在这里回复：https://github.com/leancloud/ChatKit-OC/issues/235
