### ISSUE TITLE
#error "JZTableViewRowAction must be compiled under iOS8 SDK at least"

### ISSUE THREAD

**Issue by longxianlin** [leancloud/ChatKit-OC#250]
## Base Info for this issue 

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
ChatKit的版本太低，升级到最新版，然后再参考 https://github.com/leancloud/ChatKit-OC#常见问题
