### ISSUE TITLE
\r或者\n的消息接收失败

### ISSUE THREAD

**Issue by sunlei053667** [leancloud/ChatKit-OC#252]
## Base Info for this issue 

如果用LeanEngine上NodeJs发送消息给任意用户，只要消息里面包含\r或者\r，消息接收失败。
比如发送消息为"你好\r" 或者"你好\n"，那么接收端显示的是“当前版本暂不支持查看次消息，请尝试升级APP查看”

 1. ChatKit Version：0.8.5
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
贴下你发送的完整内容，最好贴上相关发送代码。

**Comment by ChenYilong** [comment]
App层接收到消息控制台会有日志输出，格式类似下面这样，贴下：


 ```Objective-C
------ BEGIN LeanCloud IM In Command ------
content: <AVIMGenericCommand 0x1703c30c0>: {
    cmd: logs
    peerId: "qqqq"
    i: 3
    logsMessage {
      logs {
        from: "Jerry"
        data: "{"_lctype":-3,"_lcattrs":{"dev":true,"conversationType":1},"_lcfile":{"url":"http://ac-dYRQ8YfH.clouddn.com/GHjqDFEM3zd10JN8sspjHBC.mp3","objId":"58774213b123db005dd4510e","metaData":{"size":5832,"format":"mp3","duration":1.306122}}}"
        timestamp: 1484210707427
        msgId: "kBOHStHmRMiTg4E8KyezZA"
        ackAt: 1484210708091
      }
    }
}
 ```

**Comment by sunlei053667** [comment]
APP Log：
content: <AVIMGenericCommand 0x6080009c1e00>: {
    cmd: direct
    peerId: "5847ce5fac502e006bb9cca5"
    directMessage {
      msg: "{"_lctype":-1,"_lctext":"照片已经通过验证n可以开始r邂逅了"}"
      fromPeerId: "57e1ff77128fe10064e3cda7"
      timestamp: 1484300840828
      cid: "5878a06ffab00f41ddc5d640"
      id: "uxNUou6cRNih_RyVjkbWCA"
    }
}

查看log，发现"\n"变成了"n"。
问题已经解决！感谢。只要再加一个\变成"\\n"就可以了。
但是很奇怪不管发送是"\n", "\\n" ，日志都是"n"。
另外，在安卓机器上也测试了一下，安卓回车不认识"\r"。
因此最终解决方案，采用的是"\\n"来表示回车。

非常感谢！

**Comment by ChenYilong** [comment]
OK
