### ISSUE TITLE
消息列表未刷新

### ISSUE THREAD

**Issue by MrCoderMSH** [leancloud/ChatKit-OC#253]
## Base Info for this issue 

由于LCCKConversationListViewController不能够满足业务需求，所以进行了自己定制listViewController的设计，并在ViewDidLoad进行添加了如下通知：

 ```Objective-C
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(updateStatusView) name:LCCKNotificationConnectivityUpdated object:nil];
    // 当在其它 Tab 的时候，收到消息, badge 增加，所以需要一直监听
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(refresh) name:LCCKNotificationMessageReceived object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(refresh) name:LCCKNotificationUnreadsUpdated object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(refresh) name:LCCKNotificationConversationListDataSourceUpdated object:nil];

 ```

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

当从其他页面进行创建新的会话时 并且发送成功若干条信息，但是自定义的conversationListViewController没有进行刷新，可能一下几个通知未发送，现在想知道是否是少了通知的监听，或者是相关的通知发送的逻辑：

 ```Objective-C
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(updateStatusView) name:LCCKNotificationConnectivityUpdated object:nil];
    // 当在其它 Tab 的时候，收到消息, badge 增加，所以需要一直监听
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(refresh) name:LCCKNotificationMessageReceived object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(refresh) name:LCCKNotificationUnreadsUpdated object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(refresh) name:LCCKNotificationConversationListDataSourceUpdated object:nil];
 ```

**Comment by ChenYilong** [comment]
> 创建新的会话时,但是自定义的conversationListViewController没有进行刷新

贴下你怎么创建对话的代码

**Comment by MrCoderMSH** [comment]
https://github.com/leancloud/ChatKit-OC/issues/249  249这个已关闭的issue里面有创建聊天室的逻辑

**Comment by ChenYilong** [comment]
如果你采用 #249 这种方式初始化LCCKConversationListViewController 是无法触发通知的，为什么不采用继承的方式？

**Comment by MrCoderMSH** [comment]
那也就是说需要我我需要把聊天室修改成继承？但是这个不应该影响post通知吧

**Comment by MrCoderMSH** [comment]
已解决，貌似是因为 249 创建聊天室引起的   聊天室新增如下两个方法即可：`- (void)viewWillDisappear:(BOOL)animated
{
    [super viewWillDisappear:animated];
    [self.chatVC viewWillDisappear:animated];
}

- (void)viewDidDisappear:(BOOL)animated
{
    [super viewDidDisappear:animated];
    [self.chatVC viewDidDisappear:animated];
}`

**Comment by ChenYilong** [comment]
遇到此类问题，建议改为继承。
