### ISSUE TITLE
国际化不显示中文.

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#254]
1. ChatKit Version：0.8.5
 3. Language：Swift
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
所有用到国际化字符的地方,都不显示中文了.请问怎么检查?
Resources中的.string中文文件都在.

**Comment by ChenYilong** [comment]
系统是中文的吗？

是ChatKit内部View的展示？

之前版本是否正常？

**Comment by Seppuu** [comment]
系统是中文,恩,是ChatKit的View.之前正常.

**Comment by ChenYilong** [comment]
是否自定义过本地化文件所在的`Other.bundle`文件？

**Comment by ChenYilong** [comment]
如果自定义的话，命名方式确保为：`CustomizedChatKit.Other.bundle`

**Comment by Seppuu** [comment]
自定义过,然后我把它删除了.重新安装之后,依然有这个问题.

**Comment by ChenYilong** [comment]
在模拟器上试试，将模拟器设置为中文，然后将模拟器reset一下，确保不是编译缓存的问题。

**Comment by Seppuu** [comment]
在模拟器上reset之后,重新安装.问题依然在.

**Comment by ChenYilong** [comment]
官方Demo没问题，你在你机器上确认下。

**Comment by Seppuu** [comment]
和ChatKit没有关系.我关闭issue了.
