### ISSUE TITLE
奇怪的问题

### ISSUE THREAD

**Issue by BoyLiJiaWei** [leancloud/ChatKit-OC#257]
## Base Info for this issue 

接上chatkit 之后 控制台一直提示这个错
CFNetwork internal error (0xc01a:/BuildRoot/Library/Caches/com.apple.xbs/Sources/CFNetwork_Sim/CFNetwork-758.3.15/Loading/URLConnectionLoader.cpp:289)
不知道是什么原因

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by ChenYilong** [comment]
测试没发现该问题。
