### ISSUE TITLE
Crash when start record a voice message (hold the record button)

### ISSUE THREAD

**Issue by lusfold** [leancloud/ChatKit-OC#259]
## Base Info for this issue 

 1. ChatKit Version：0.8.5
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug

## 1. How to repeat the problem.

Enter ConversationViewController -> Hold record voice message button -> Crash

## 4. Here is my Debug log

Finally i found it was Mp3Recorder.m (Line 77: [_recorder record]) lead to this crash problem.

```
AVFAudio`-[AVAudioRecorder record]:
    0x1ab41b17c <+0>:  stp    x20, x19, [sp, #-32]!
    0x1ab41b180 <+4>:  stp    x29, x30, [sp, #16]
    0x1ab41b184 <+8>:  add    x29, sp, #16              ; =16 
    0x1ab41b188 <+12>: mov    x19, x0
    0x1ab41b18c <+16>: bl     0x1a721cc50
    0x1ab41b190 <+20>: adrp   x8, 47667
    0x1ab41b194 <+24>: ldrsw  x8, [x8, #644]
    0x1ab41b198 <+28>: ldr    x1, [x19, x8]
    0x1ab41b19c <+32>: movz   x2, #0
    0x1ab41b1a0 <+36>: fmov   d0, #-1.00000000
    0x1ab41b1a4 <+40>: mov    x0, x19
    0x1ab41b1a8 <+44>: bl     0x1ab41b1e0               ; recordQueue(AVAudioRecorder*, AudioRecorderImpl*, double, AudioTimeStamp const*)
    0x1ab41b1ac <+48>: mov    x20, x0
    0x1ab41b1b0 <+52>: mov    x0, x19
    0x1ab41b1b4 <+56>: bl     0x1a721cc54
    0x1ab41b1b8 <+60>: cmp    w20, #0                   ; =0 
    0x1ab41b1bc <+64>: cset   w0, eq
    0x1ab41b1c0 <+68>: ldp    x29, x30, [sp, #16]
    0x1ab41b1c4 <+72>: ldp    x20, x19, [sp], #32
    0x1ab41b1c8 <+76>: ret    
    0x1ab41b1cc <+80>: mov    x20, x0
    0x1ab41b1d0 <+84>: mov    x0, x19
    0x1ab41b1d4 <+88>: bl     0x1a721cc54
    0x1ab41b1d8 <+92>: mov    x0, x20
    0x1ab41b1dc <+96>: bl     0x1a721c808
```

**Comment by ChenYilong** [comment]
Sorry I can't repeat your problem, can you give me a demo? here is my email luohanchenyilong@163.com

then you should make sure this :

After iOS10 Before you access privacy-sensitive data like Camera, Contacts, and so on, you must ask for the authorization, your app will crash when you access them.Then Xcode will log like:



https://github.com/ChenYilong/iOS10AdaptationTips#security

**Comment by lusfold** [comment]
THX for your advice.
Problem solved by asking for the authorization.
