### ISSUE TITLE
按住说话 那个按钮，左边不能及时响应，右边能立即响应

### ISSUE THREAD

**Issue by GitterYang** [leancloud/ChatKit-OC#26]
按住说话 那个按钮，左边不能及时响应，右边能立即响应。同一个按钮，怎么会出现这种情况？

**Comment by CoderEic** [comment]
真机上，iPhone6

**Comment by ChenYilong** [comment]
是个Bug，后期版本会修复掉

**Comment by CoderEic** [comment]
我想知道怎么才能修复这个bug？问题到底能出在哪？

**Comment by ChenYilong** [comment]
还没看原因，不过确实是个Bug

**Comment by CoderEic** [comment]
好的，如果知道原因了，麻烦告知一声，谢谢

**Comment by GitterYang** [comment]
self.interactivePopGestureRecognizer.delaysTouchesBegan = NO; 与navigationBar的系统手势冲突了，添加这个可以解决
