### ISSUE TITLE
聊天界面布局问题

### ISSUE THREAD

**Issue by Geory** [leancloud/ChatKit-OC#265]
请问聊天界面布局根据

 ```Objective-C
   [self.tableView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.and.left.and.width.equalTo(self.view);
        make.bottom.equalTo(self.chatBar.mas_top);
    }];
    [self.chatBar mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.and.right.and.bottom.equalTo(self.view);
        make.height.mas_greaterThanOrEqualTo(@(kLCCKChatBarMinHeight));
    }];
 ```

就能确定布局吗，为什么按这个设置后chatbar会置顶到上方导致没有tableview的显示空间(主要是textView被拉伸到最大)，也就是mas_greaterThanOrEqualTo没按最小的显示，请问还需要设置什么吗？

**Comment by ChenYilong** [comment]
textView 的约束呢？

**Comment by Geory** [comment]
[self.textView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(self.voiceButton.mas_right).with.offset(offset);
        make.right.equalTo(self.faceButton.mas_left).with.offset(-offset);
        make.top.equalTo(self.inputBarBackgroundView).with.offset(kChatBarTextViewBottomOffset);
        make.bottom.equalTo(self.inputBarBackgroundView).with.offset(-kChatBarTextViewBottomOffset);
        make.height.mas_greaterThanOrEqualTo(kLCCKChatBarTextViewFrameMinHeight);
    }];
也是按原来设置的

**Comment by Geory** [comment]
@ChenYilong  还需要什么约束使其初始界面的布局是正常的？

**Comment by ChenYilong** [comment]
如果关于ChatKit的使用问题，是原理相关的问题，那么就建议你看源代码，自行理解。
