### ISSUE TITLE
ChatKit 语音发送失败

### ISSUE THREAD

**Issue by sunlei053667** [leancloud/ChatKit-OC#267]
## Base Info for this issue 

两个用户同时在线，互相发送消息。发送文本都可以通过，发送语音失败。

 1. ChatKit Version：0.8.5
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

## 1. How to repeat the problem.

发送语音消息，录制成功，但是发送过程失败。点击感叹号重新发送，问题依然存在。
## 4. Here is my Debug log

在下面这个函数中

 ```Objective-C
- (void)sendMessage:(AVIMMessage *)message
             option:(AVIMMessageOption *)option
      progressBlock:(AVProgressBlock)progressBlock
           callback:(AVIMBooleanResultBlock)callback
{
        //这个时候file的内存状态如图
        if (file) {
            if ([file isDirty]) {
                /* File need to be uploaded */
                [file saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
                //这个地方产生错误， error：400 file not found
              

}
 ```

 //这个时候file的内存状态如图
![932e0d66-2e46-436c-b4c0-15987f9489a8](https://cloud.githubusercontent.com/assets/8157807/22875705/1d8f7366-f208-11e6-896b-c6687f1cbd4a.png)

**Comment by sunlei053667** [comment]
打扰了，龙哥 ，我已经解决了，是我的问题。我之前去修改库里面照片的压缩率。照片跟声音都被当作文件处理，我当时只考虑到了照片的情况，没有考虑到声音也是文件，所以声音文件就有问题了。所以才会有这个问题。

**Comment by ChenYilong** [comment]
ok
