### ISSUE TITLE
LCCKChatTextMessageCell

### ISSUE THREAD

**Issue by xueqiulou** [leancloud/ChatKit-OC#27]
源代码里没有 MLLinkLabel 这个类文件,项目  LCCKChatTextMessageCell.h里 却用到了,能不能把这个类提交一下?

**Comment by ChenYilong** [comment]
最新版v0.4.1已经修复了

**Comment by xueqiulou** [comment]
我两个小时前down下来的代码里还是没有这个类呀?

**Comment by ChenYilong** [comment]
这是Pod依赖： https://github.com/leancloud/ChatKit-OC/blob/297e9f76462f03f92c1b997a2e0f096a1931a42f/ChatKit.podspec#L26

这是头文件引用：

https://github.com/leancloud/ChatKit-OC/blob/a3af0dea002d052270602f2a5fa6d05f607d35ff/ChatKit/Class/Module/Conversation/View/ChatMessageCell/LCCKChatMessageCell.h#L17

**Comment by ChenYilong** [comment]
@xueqiulou

**Comment by xueqiulou** [comment]
我可能要改源码里的一些逻辑,所以我没用pod,直接down的源码,里边用到了这个类,但是源码里没有,我刚pod了一遍里边也没有这个类呀,pod的代码版本是0.0.5(0.4.2是哪个版本号?),而且pod下来的代码里没有用到这个类,这是啥情况?谢谢啦

**Comment by ChenYilong** [comment]
0.0.5 是很早的版本了，0.4.2是最新的pod版本。

**Comment by ChenYilong** [comment]
手动安装的话，要添加的依赖库有这些：

https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit.podspec#L16

**Comment by ChenYilong** [comment]
加我 QQ 1356701892

**Comment by ChenYilong** [comment]
已修复
