### ISSUE TITLE
avatarImageViewCornerRadiusBlock在Swift中Crash

### ISSUE THREAD

**Issue by mokai** [leancloud/ChatKit-OC#276]
## Base Info for this issue 

设置avatarImageViewCornerRadiusBlock后在LCCKChatMessageCell的avatarImageView方法中调用avatarImageViewCornerRadiusBlock(avatarImageViewSize);时报错：EXC_BAD_INSTRUCTION(code=EXC_ARM_UNDEFINED,...)

然后看到avatarImageViewCornerRadiusBlock定义时其属性是assign，是不是Block没有copy被释放了。然而我在OC中试是正常的~

 1. ChatKit Version：0.8.5
 2. App-ID: XX
 3. Language：Swift
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by tang3w** [comment]
的确应该用 copy 来声明属性，谢谢反馈，我们会尽快修复该问题。

**Comment by tang3w** [comment]
@mokai 请帮忙 checkout #277 的改动，确认一下是否修复了这个问题。

**Comment by mokai** [comment]
好的

**Comment by mokai** [comment]
@tang3w 冒味地问句，我是用pod集成的，是不是需要手动集成才能使用修改后的代码

**Comment by tang3w** [comment]
Pods 也是源码文件，只需覆盖 PR 中改动的文件即可。然后再 Clean 然后重新编译一下。

**Comment by mokai** [comment]
OK，已正常，接下来等Pod上发布新的Version吗

**Comment by tang3w** [comment]
是的，我们会马上发一个新版本。

**Comment by tang3w** [comment]
发布后会在此通知您。
