### ISSUE TITLE
导入报could not build module ChatKit 的错

### ISSUE THREAD

**Issue by zaoqilai** [leancloud/ChatKit-OC#285]
![2017-02-27 4 50 33](https://cloud.githubusercontent.com/assets/20429892/23354705/6a4434e8-fd0d-11e6-9168-5a8db325fbe1.png)

**Comment by tang3w** [comment]
请提供详细的编译日志。

**Comment by zaoqilai** [comment]
OC工程, 是之前用了一个swift的第三方框架,所以在podfile中有use_frameworks! , 我把这个删掉用正常运行 .

看了https://forum.leancloud.cn/t/ios-lldb-include-non-modular-header/3842/11这个问题才考虑到.

**Comment by tang3w** [comment]
好的，谢谢反馈。
