### ISSUE TITLE
无法收到离线消息推送

### ISSUE THREAD

**Issue by liyukuang** [leancloud/ChatKit-OC#288]
## Base Info for this issue 
 1. ChatKit Version：0.8.14
 2. App-ID: XX
 3. Language：Swift
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Q-A

请问Leancloud账户开发版能不能接收到Chatkit的离线消息推送， 还是说必须升级到商业版才可以。我现在按照要求配置的
{"alert":"您有新的消息","badge":"Increment","_profile":"dev"}
但无法收到消息，在线消息是可以收到的。

另外我知道暂态聊天室是无法收到推送的是吧，请问怎么取消收到消息时候的提示音？作为暂态聊天室，希望用户不要被打扰到

**Comment by heyz-lzj** [comment]
你好 开发版能不能接收到Chatkit的离线消息推送? 我这里是可以收到其他推送,唯独收不到chatkit IM部分的推送

**Comment by liyukuang** [comment]
开发版可以接收的。注意暂态聊天室是不支持推送的
