### ISSUE TITLE
消息缓存逻辑建议: SDK中消息缓存最后一条消息的breakpoint一定是断的, 所以先服务器拉取最后一条消息, 然后在根据这条消息id拉取缓存数据, 就会忽略缓存导致每次都走服务器拿数据。希望:首次进入Conversation, 如果消息和服务器一致则拉取本地，不一致则拉取服务器。

### ISSUE THREAD

**Issue by huangshun11** [leancloud/ChatKit-OC#293]
## Base Info for this issue 

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by liyukuang** [comment]
请问这个可以怎么修复么，每次都要等着加载真的非常蛋疼啊
