### ISSUE TITLE
LCCKConversationViewController tableView top offSet 

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#30]
LCCKConversationViewController 中的tableView 有顶部位移现象. 
不知道未来的版本会不会适配.
当下,我通过
self.edgesForExtendedLayout = UIRectEdgeNone;
暂时解决了.

**Comment by ChenYilong** [comment]
请提供 CocoaPods 版本号以及截图。

**Comment by Seppuu** [comment]
因为是swift项目,我手动安装了ChatKit
![image](https://cloud.githubusercontent.com/assets/12640162/17618916/ebbe5620-60b4-11e6-866b-a672673c14de.png) 以上是截图.

**Comment by ChenYilong** [comment]
推测你的项目结构应该是一个tabbar，一个navigation，下面四个ViewController，这四个ViewController没有被navigationViewController包装，共享一个navigationViewController，是不是这样？

**Comment by Seppuu** [comment]
对,但是.这部分是用的示例代码.包装了navigationViewController
![image](https://cloud.githubusercontent.com/assets/12640162/17619212/6ab87324-60b6-11e6-963d-c2f0cf84c21f.png)
我下载的版本是半个月前的.刚刚看到已经有相似的issue.我想可能修复了,我更新一下.

**Comment by ChenYilong** [comment]
建议使用 CocoaPods 安装，方便后期bug修复后及时更新。现在项目处于完善期，更新频率很高，如果有遇到bug，可以查看下commit，然后按需更新版本号。

**Comment by Seppuu** [comment]
swift项目用CocoaPods安装ChatKit现在可以正常import了吗? 之前在论坛上看到说暂时只能手动.

**Comment by ChenYilong** [comment]
之前论坛的问题修复了，你再试试，如果遇到问题可以向我反馈，我会及时修复的。

**Comment by Seppuu** [comment]
ChatKit 0.4.2 聊天界面顶部有偏移. 项目是Swift的.
![image](https://cloud.githubusercontent.com/assets/12640162/17654062/357dc430-62d1-11e6-99d4-02964a87cd59.png)

**Comment by ChenYilong** [comment]
今天发个修复版本。

**Comment by ChenYilong** [comment]
v0.5.1已修复，请更新。

**Comment by Seppuu** [comment]
我更新到了0.5.3 但是bulid问题很多.
![image](https://cloud.githubusercontent.com/assets/12640162/17727795/2c42981e-648e-11e6-9945-1703a1826982.png)
![image](https://cloud.githubusercontent.com/assets/12640162/17727809/3d62d8e8-648e-11e6-9501-391f8a0f557b.png)

**Comment by ChenYilong** [comment]
你确认下，是不是Pod没有成功，怎么连Masonry都找不到，是有用户已经Build、运行成功的。建议Clean、删缓存，重新pod.

**Comment by ChenYilong** [comment]
0.6.0版本已发布，请更新。

**Comment by Seppuu** [comment]
0.6.0 build成功, LCCKConversationViewController顶部消息位移的BUG也没了.我关闭issue了.谢谢.
