### ISSUE TITLE
请把ChatKit中使用的SDWebImage版本升级到最新版！

### ISSUE THREAD

**Issue by koalahl** [leancloud/ChatKit-OC#300]
hi，

请把ChatKit pod file中使用的SDWebImage版本升级到最新版，因为sdwebimage4.0.x解决了一些bug。不要固定用3.8.0.

**Comment by tyeen** [comment]
+1

**Comment by ChenYilong** [comment]
fixed in   [CYLChatKit](https://github.com/ChenYilong/CYLChatKit) ,
change log:
> v2.1.7 update SDWebImage version to 4.4.1

https://github.com/ChenYilong/CYLChatKit/releases

**Comment by koalahl** [comment]
(⊙﹏⊙) 感谢更新。虽然上一个项目已经结束了。

当时的问题应该是在SD解压缩图片时内存暴涨。。
