### ISSUE TITLE
Swift project pod 'ChatKit' issue

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#31]
Swift 项目 pod ChatKit 有一点问题.
[!] The 'Pods-XianHui' target has transitive dependencies that include static binaries: (/Users/Dan/Documents/XianHui/Pods/AVOSCloud/libAVOSCloud.a and /Users/Dan/Documents/XianHui/Pods/AVOSCloudIM/libAVOSCloudIM.a)

![image](https://cloud.githubusercontent.com/assets/12640162/17619544/8e48f460-60b8-11e6-85c6-a980402da8db.png)
请问如何处理?

**Comment by ChenYilong** [comment]
嗯，这是动态库的问题，请问你的podfile里有没有指定 use_frameworks!

**Comment by Seppuu** [comment]
platform :ios, '8.0'
use_frameworks!

target 'XianHui' do
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'AVOSCloudCrashReporting'
pod 'ChatKit'

end

是这样的.

**Comment by ChenYilong** [comment]
ChatKit已经依赖了头两个，请勿重复添加 https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit.podspec

**Comment by Seppuu** [comment]
pod 添加OK了.谢谢你.
