### ISSUE TITLE
ChatKit 聊天记录 本地缓存

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#32]
请问ChatKit现在有聊天记录的本地缓存记录吗? 现在是每次进入聊天页面都从网络加载.

**Comment by ChenYilong** [comment]
聊天记录是有缓存的，你可以开启飞行模式，看下效果，依然可以展示消息记录，且能够下拉刷新，但是为了确保消息的连续性，所以决定每次进入聊天室只要有网就都从网络加载。第二次，以及之后的消息就会优先从缓存加载，只在消息有中断时，才从服务端拉取。这样才能确保每次加载到的消息都是最新的，这样，下拉刷新才会保证下拉到的消息是没有中断的。
