### ISSUE TITLE
关于LCCKConversationListViewController 自定义的疑问.

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#33]
我想将会话列表加上几个自己的需求.就像这样.
![img_0868](https://cloud.githubusercontent.com/assets/12640162/17659988/d9528ee2-6308-11e6-91de-5653a472a084.PNG)

于是自定义一个ConversationListVC:LCCKConversationListViewController.然后遇到一个问题,就是ChatKit中已经在typedef中写定了回调的类型是LCCKConversationListViewController.
比如 

/*!
 *  选中某个对话后的回调
 *  @param conversation 被选中的对话
 */
typedef void(^LCCKDidSelectConversationsListCellBlock)(NSIndexPath *indexPath, AVIMConversation *conversation, LCCKConversationListViewController *controller);

当我使用它时,我需要将controller 转化成子类吗? 会有什么问题吗?

比如
[[LCChatKit sharedInstance] setDidSelectConversationsListCellBlock:^(NSIndexPath *indexPath, AVIMConversation *conversation, LCCKConversationListViewController *controller) {
        [[self class] exampleOpenConversationViewControllerWithConversaionId:conversation.conversationId fromNavigationController:controller.navigationController];
    }];

**Comment by ChenYilong** [comment]
子类化没问题，大胆写。
