### ISSUE TITLE
红包UI显示测试Demo，怎么去掉或者修改

### ISSUE THREAD

**Issue by BoyLiJiaWei** [leancloud/ChatKit-OC#338]
## Base Info for this issue 

![wechatimg2](https://user-images.githubusercontent.com/13958008/28860397-03ae9442-778f-11e7-9d44-c331fad43d40.jpeg)

 1. ChatKit Version：0.7.17
 2. App-ID: XX
 3. Language：Objective-C
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash、Bug、Enhancement（希望能支持一个新需求）、Q-A

**Comment by BinaryHB** [comment]
已和云账户确认，这个暂时无法更改。因为这部分 SDK 未放出来开源。

如果您申请的他们账户的话，这个里会自动显示为您在云账户的注册应用信息。

**Comment by BoyLiJiaWei** [comment]
可以隐藏吗




发自网易邮箱大师
在2017年08月02日 15:14，David Duan 写道：

已和云账户确认，这个暂时无法更改。因为这部分 SDK 未放出来开源。

如果您申请的他们账户的话，这个里会自动显示为您在云账户的注册应用信息。

**Comment by BinaryHB** [comment]
也无法隐藏的。他们开发这套红包 UI SDK，是希望用户多多开通他们的账户。

您要更改或者隐藏的话，可能需要自己再开发一下了。

**Comment by BoyLiJiaWei** [comment]
知道了，谢谢




发自网易邮箱大师
在2017年08月02日 15:18，David Duan 写道：

也无法隐藏的。他们开发这套红包 UI SDK，是希望用户多多开通他们的账户。

您要更改或者隐藏的话，可能需要自己再开发一下了。
