### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by liyukuang** [leancloud/ChatKit-OC#34]
ChatKit-OC/ChatKit-OC/Example/Class/Module/CustomMessage/View/LCCKVCardView.m:42:28: Use of undeclared identifier 'LCCK_CONVERSATIONVIEWCONTROLLER_BACKGROUNDCOLOR'

ChatKit-OC/ChatKit-OC/Example/Class/Module/CustomMessage/View/LCCKVCardView.m:43:40: Use of undeclared identifier 'LCCK_CONVERSATIONVIEWCONTROLLER_BACKGROUNDCOLOR'

ChatKit-OC/ChatKit-OC/Example/Class/Module/CustomMessage/View/LCCKVCardView.m:48:25: Property 'lcck_cornerRadius' not found on object of type 'UIImageView *'

麻烦求解！另外可不可以把文档写的更加详细一点，我正尝试集成到swift project里面，对oc很不熟看起来十分费力，多谢！

**Comment by ChenYilong** [comment]
这三行出错的地方都可以删除，不影响运行效果。 https://github.com/leancloud/ChatKit-OC/compare/c5d17c81d971...5fdf721f5c56
