### ISSUE TITLE
网络状态提醒

### ISSUE THREAD

**Issue by clarenceli** [leancloud/ChatKit-OC#35]
每次从后台切换到前台的时候，网络状态提醒的小红条都会出现一小会再消失，可否换一种机制？

**Comment by ChenYilong** [comment]
可以，最近做下，会模仿下微信的逻辑。

**Comment by clarenceli** [comment]
这个issue能不能先处理下

**Comment by ChenYilong** [comment]
ok，我处理下。下午发个版本。

**Comment by ChenYilong** [comment]
v0.7.12已发布，退至后台后，不再检查Session是否断开。 https://github.com/leancloud/ChatKit-OC/commit/8872dcf9657d8c786af532c4898fd3504e18c37b

**Comment by ChenYilong** [comment]
我自己测试是没有问题了，有问题再开启吧。
