### ISSUE TITLE
MWPhotoBrowser.bundle not found 麻烦作者看看这个错误

### ISSUE THREAD

**Issue by 542604974** [leancloud/ChatKit-OC#36]
error: Resource "/Users/apple/Library/Developer/Xcode/DerivedData/ChatKit-OC-brvjzpdxmoovotawnajeevzbblfb/Build/Products/Debug-iphonesimulator/MWPhotoBrowser.bundle" not found. Run 'pod install' to update the copy resources script.

**Comment by ChenYilong** [comment]
我见到已经有很多人Pod成功了，请尝试清理缓存，clean后，再次pod

**Comment by 542604974** [comment]
升级pod到1.1.0可以解决问题，本来我是1.0.0版本。

**Comment by 542604974** [comment]
升级pod命令sudo gem install -n /usr/local/bin cocoapods --pre

**Comment by ChenYilong** [comment]
运行成功了吧，多谢提供解决方法。

**Comment by JianboYan** [comment]
@ChenYilong hi 我这边是1.2.0 但是在编译的时候还是出现这个问题了
