### ISSUE TITLE
 CocoaPods 安装问题询问

### ISSUE THREAD

**Issue by BaiCanLin** [leancloud/ChatKit-OC#38]
cocospod 更新失败(⊙o⊙)…

**Comment by ChenYilong** [comment]
我这边没问题，我也看到好多人pod成功了，你具体是什么错误？

**Comment by BaiCanLin** [comment]
提示pod 'ChatKit', :path => '../' 路径不存在, 这个"CYLTableViewRowAction", "1.0.0"找不到

**Comment by ChenYilong** [comment]
你的 CocoaPods 版本是多少，我这里是1.0.0，是可以的。

**Comment by ChenYilong** [comment]
请问你用的是不是 1.0.1以上版本的？

**Comment by ChenYilong** [comment]
如果是1.0.1以上版本，确实会这个问题，参考 CocoaPods 的官方 issue：

https://github.com/CocoaPods/CocoaPods/issues/5623

（如果不行，再参考 https://github.com/CocoaPods/CocoaPods/issues/5427 ）

**Comment by DemonFengYuXiang** [comment]
我的pod版本是1.0.1, 我进入ChatKit-OC中进行pod install，提示 [!] Unable to find a specification for `CYLTableViewRowAction (= 1.0.0)` . 麻烦看一下是不是服务器上的代码是不是出错了

**Comment by ChenYilong** [comment]
你在你本机上把

 ```Objective-C
pod "CYLTableViewRowAction", "1.0.0"
 ```

改为：


 ```Objective-C
pod 'CYLTableViewRowAction'
 ```
试试

**Comment by ChenYilong** [comment]
试着


 ```Objective-C
pod search CYLTableViewRowAction
 ```


如果发现找不到，那么就用下面的命令安装


 ```Objective-C
pod install 
 ```




就别用这个安装了


 ```Objective-C
# 如果提示找不到库，则可去掉 --no-repo-update
pod update --verbose --no-repo-update
 ```

**Comment by ChenYilong** [comment]
这里有个朋友说他删除了BuildPhases目录下的Embed Frameworks，然后可以运行了。

http://www.weibo.com/1692391497/E5LxQvTSy?type=comment

**Comment by DemonFengYuXiang** [comment]
恩，当我在所在的文件夹进行pod update后，然后进行pod install后就可以了

**Comment by ChenYilong** [comment]
Ref：https://github.com/leancloud/ChatKit-OC/issues/36

**Comment by ChenYilong** [comment]
由于 CocoaPods 1.0版本，做了较大改动，可能造成非1.0 CocoaPods 版本下pod失败，该问题可通过升级到1.0解决。并且，我已经将Pod文件夹一并上传，现在运行Demo，已经不需要pod，如果之前遇到过安装问题，现在请重试。

**Comment by GouWeiBaCao** [comment]
如果是1.0.1以上版本，本地依赖，会报 no method error，这个是 CocoaPods 官方的Bug，应该会在 CocoaPods 下个版本修复。参考 CocoaPods 的官方 issue：     我也碰到这个bug 现在项目打开都有问题,怎么解..急等 qq 1062080667   具体的是  NoMethodError - undefined method `path' for nil:NilClass
