### ISSUE TITLE
打开 聊天 client 失败 什么原因

### ISSUE THREAD

**Issue by xueqiulou** [leancloud/ChatKit-OC#39]
报错!!!
error == Error Domain=NSURLErrorDomain Code=-1001 "请求超时。" UserInfo={NSUnderlyingError=0x1562139c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://router-g0-push.leancloud.cn/v1/route?appId=AtwJtfIJPKQFtti8D3gNjMmb-gzGzoHsz&ip=true&secure=1, NSErrorFailingURLKey=https://router-g0-push.leancloud.cn/v1/route?appId=AtwJtfIJPKQFtti8D3gNjMmb-gzGzoHsz&ip=true&secure=1, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=请求超时。}

**Comment by ChenYilong** [comment]
只此一次，还是频繁的？

**Comment by xueqiulou** [comment]
用4G网可以,公司的WiFi就不行,聊天服务器对网络有限制吗,公司的wifi打开网页都没有问题

**Comment by ChenYilong** [comment]
没有限制，应该是网络质量太差引起连接和消息收发失败

1，请在 very bad net并且无法发消息情况下，测试下能否用 safari 打开 https://api.leancloud.cn/1/ping
2，因为正常3%的网络丢包就会引起网络变慢的感受，而very bad net的丢包率为10%，如果可以，请将in packet loss 和 out packat loss 改成1%，再测试。

详情可参考：
https://blog.leancloud.cn/1683/

**Comment by ChenYilong** [comment]
@xueqiulou 测试的如何了？

**Comment by xueqiulou** [comment]
可以了,应该是我们的网络不是太好,谢啦
