### ISSUE TITLE
会话详情页重连时需要刷新消息

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/ChatKit-OC#397]
会话详情页面中正在聊天的两个 Client，其中 A 退出后台，B 正在给 A 发送消息。
A 从后台返回会话会话详情，没有刷新最新的消息。

用户社区反馈:  https://forum.leancloud.cn/t/ios-chatkit/18421

**Comment by htxian** [comment]
原因是2.1.1+的
LCCKSessionService的
- (void)conversation:(AVIMConversation *)conversation didReceiveUnread:(NSInteger)unread; 被注释了
另外
- (void)conversation:(AVIMConversation *)conversation didReceiveCommonMessage:(AVIMMessage *)message;
- (void)conversation:(AVIMConversation *)conversation didReceiveTypedMessage:(AVIMTypedMessage *)message;
这两个delete在后台时没有调用。

**Comment by zapcannon87** [comment]
Fixed in v2.3.0
