### ISSUE TITLE
LCCKConversationViewController crash!!!

### ISSUE THREAD

**Issue by OHeroJ** [leancloud/ChatKit-OC#398]
## Base Info for this issue 

version: 2.2.2,
 ```
- (void)sendWelcomeMessageIfNeeded:(BOOL)isFirstTimeMeet
```
中的 `[self sendTextMessage:welcomeMessage];` 找不到方法的实现

 1. ChatKit Version：2.2.2
 2. App-ID: XX
 3. Language：swift
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Crash

## 1. How to repeat the problem.

跟新人聊天 crash

## 2. Please help me in this way.

实现这个方法

**Comment by zapcannon87** [comment]
Fixed in v2.3.0
