### ISSUE TITLE
收起chatbar

### ISSUE THREAD

**Issue by RtzX** [leancloud/ChatKit-OC#41]
聊天界面时.点击空白区域或者 其他操作,关闭chatbar.. 所以应该提供一个 可以主动关闭chatbar 的接口

**Comment by ChenYilong** [comment]
好建议，下版本就加上，。

**Comment by ChenYilong** [comment]
之前我是有添加点击空白处收缩键盘的，不过后来我给超链接添加Tap手势时，为避免手势冲突禁用了这个动作。下个版本加上。

**Comment by ChenYilong** [comment]
fix in CYLChatKit (version 2.1.8)
changeLog:

> v2.1.8 when tap message cell blank area ,dissmiss chatbar
