### ISSUE TITLE
ChatKit-ReactNative

### ISSUE THREAD

**Issue by huliyou** [leancloud/ChatKit-OC#42]
Did you have any plan to develop react-native SDK ？

**Comment by ChenYilong** [comment]
Not planned, this is our JS engineer @leeyeh .Maybe he can help you. He wrote some demos for react-native like https://github.com/leancloud/react-native-installation-demo

**Comment by huliyou** [comment]
@leeyeh Do you interest in developing react-native SDK for ChatKit ? I think it must be cool !

**Comment by leeyeh** [comment]
Sounds interesting, but not our priority at this moment.

**Comment by leeyeh** [comment]
Actually, there has already been some fantastic libraries focus on chat UI for React Native such as https://github.com/FaridSafi/react-native-gifted-chat

Currently, we are focusing our efforts on polishing the JavaScript Realtime SDK, which plays well as the Model layer for React Native chat apps.
