### ISSUE TITLE
下载Demo，更新pods后报错"google/protobuf/LCIMTimestamp.pbobjc.h" file not found

### ISSUE THREAD

**Issue by xiongyoudou** [leancloud/ChatKit-OC#44]
您好，感谢您对开源！
从github上下载后，再更新pods，提示报错"google/protobuf/LCIMTimestamp.pbobjc.h" file not found，其实该文件是存在的，但是不知道是否需要做什么设置才可以让编译器识别出来！

**Comment by ChenYilong** [comment]
请问你的  CocoaPods 版本是多少，我这边是1.0.0，表示pod没问题，建议你删 `Podfile.lock` 和 `Pods` 文件夹，clean项目，删缓存，重新pod试下。

**Comment by xiongyoudou** [comment]
谢谢回复！删 Podfile.lock 和 Pods 文件夹，clean项目，删缓存这些都试了，还是同样的错误。我这边pods版本是0.36.4，不知道会不会有影响，现在pods升级不成功！

**Comment by ChenYilong** [comment]
那就请尝试升级下 CocoaPods 吧，暂时还未有人遇到与你一样的错误，已经有很多人运行成功。

**Comment by xiongyoudou** [comment]
好的，谢谢

**Comment by ChenYilong** [comment]
请问最后怎么解决的？

**Comment by xiongyoudou** [comment]
升级pods解决的呢
