### ISSUE TITLE
对话列表昵称会有“闪变”效果：先显示id，网络请求成功后再显示昵称，如何禁用

### ISSUE THREAD

**Issue by clarenceli** [leancloud/ChatKit-OC#45]
setFetchProfilesBlock方法的实现替换成App 的 API 同步查询后，消息列表的用户名称会从clientId闪变成真正的用户名，第二次拿缓存则不会

**Comment by ChenYilong** [comment]
这个是我这样设计的，我感觉先显示id，然后，再显示昵称，会比先什么都不显示，再显示用户名会友好一点。第二次由于直接走缓存，所以有网络请求的延迟，所以不会有这个效果。请问你是不是感觉我这种作法不合理？请描述下你希望达到的效果。

**Comment by clarenceli** [comment]
刚好这个id属于对于我们系统来说是敏感数据，所以不能让他显示出来。

**Comment by ChenYilong** [comment]
嗯，了解了，我给你个开关，你可以把这个闪变的效果禁用掉。稍等，我发个版本。

**Comment by ChenYilong** [comment]
请问，单聊时，你在网络请求前，想让昵称栏填什么，因为ChatKit此时只知道id，如果不显示id，那么显示空白，没问题吧。

**Comment by clarenceli** [comment]
我这边这样处理没问题

**Comment by ChenYilong** [comment]
发布了 v0.7.5，支持了禁止预览userId，

用法如下：
https://github.com/leancloud/ChatKit-OC/blob/1a2ebb151b6c7ae3053b056fc6b1190ca644ff24/ChatKit-OC/Example/LCChatKitExample.m#L146

默认会显示一个固定的字符串 `[该用户未设置昵称]`，如果不想显示该字符串，请到本地化文件，并将`nickNameIsNil` 对应的字符串设为空。

自定义本地化文件方法见

 [这里](https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit%20自定义业务.md#国际化与本地化)

**Comment by ChenYilong** [comment]
有一些用户的userId（clientId）是有意义的，比如微信这种，微信id是有意义的，而非随机生成的，这些用户就可以使用默认的设置：开启预览userId（clientId），而对于userID（clientId）是无意义的用户，就可以禁用该功能。

**Comment by ChenYilong** [comment]
已添加解决方案
