### ISSUE TITLE
功能需求：望添加对话的已读未读状态

### ISSUE THREAD

**Issue by MrCoderMSH** [leancloud/ChatKit-OC#47]
如题。项目需求需要知道每条对话的送达以及已读状态。另外、是否可以把聊天室的显示时间的灰色字条开放成可定义的单独消息样式。。

**Comment by ChenYilong** [comment]
对于时间戳的自定义，目前支持的是自定义这两个属性：时间分割线文字颜色、时间分割线背景色，不知道这个能否满足你的需求，如果不能，请告知你需要达到的效果，我可以默认就支持你的效果。

详细见： [《文档》](https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit%20自定义样式.md#聊天消息)

**Comment by MrCoderMSH** [comment]
比如 微信撤回某条消息，或者是群聊有好友加入出现的提示 使用时间戳的灰条来显示不同的文字

**Comment by ChenYilong** [comment]
这个可以把这类的提示消息使用自定义消息的方式做，然后自定义cell。可以参考 [《文档－自定义消息 》]( https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit%20自定义业务.md#自定义消息 ) 。下周我会把这个需求直接实现下，这周还没时间做。不过我做的话，也是这个思路，你如果着急的话，可以用自定义消息实现下。也欢迎提PR。

**Comment by ChenYilong** [comment]
目前 message 是支持送达状态的，但是还不支持已读状状态，支持已读状态，排期排到了下周或下下周。我可以先把送达状态给展示出来，等之后支持了已读未读状态，再添加上。这个送达状态展示也是得下周做。你们什么时候上线？

**Comment by MrCoderMSH** [comment]
好的，提示消息可以自定义cell实现。已读状态我们先fire掉这个功能了，就在等你们做呢。。。没有实现思路  哈哈

**Comment by ChenYilong** [comment]
ok。

**Comment by ChenYilong** [comment]
移到这里讨论 ： https://github.com/leancloud/ChatKit-OC/issues/25
