### ISSUE TITLE
关于消息列表问题，创建一个群聊如果不发言就在消息列表找不到，怎么能不发言也能看到

### ISSUE THREAD

**Issue by whytimber** [leancloud/ChatKit-OC#48]
关于消息列表问题，创建一个群聊如果不发言就在消息列表找不到，怎么能不发言也能看到

**Comment by ChenYilong** [comment]
由于ChatKit没有用到存储功能，所以这个需要你将对话id（CoversationId），存到你们的服务器上，然后启动APP后，从你们的服务端获取到id，然后由id fetch到conversation ，fetch方法参考：https://github.com/leancloud/ChatKit-OC/blob/1a2ebb151b6c7ae3053b056fc6b1190ca644ff24/ChatKit/Class/LCChatKit.m#L305 ，之后将Coversation插入到ConversationList中去，插入方法参考：https://github.com/leancloud/ChatKit-OC/blob/1a2ebb151b6c7ae3053b056fc6b1190ca644ff24/ChatKit-OC/Example/LCChatKitExample.m#L664  。

**Comment by ChenYilong** [comment]
已添加解决方案。

**Comment by whytimber** [comment]
谢谢了
