### ISSUE TITLE
删除插件后程序crash

### ISSUE THREAD

**Issue by clarenceli** [leancloud/ChatKit-OC#49]
我把demo的VCard那个plugin删掉后，点击more view一直闪退，删除方法按照你文档写的把+load方法去掉。

**Comment by ChenYilong** [comment]
我看下

**Comment by ChenYilong** [comment]
自定义inputView时，你不能直接从2开始，你删了VCard，VCard是1，然后改背景是2。要么你把改背景那个也删了，要么你把改背景的type值改为1. https://github.com/leancloud/ChatKit-OC/blob/6d56133f99711d2a8594077d7c68f1a6d77cc802/ChatKit-OC/Example/Class/Module/Customize/CustomizedConversationBackground/LCCKInputViewPluginConversationBackground.h#L18

**Comment by clarenceli** [comment]
那假如1，2，3我抽掉了2，这样就没问题的吧？

**Comment by ChenYilong** [comment]
也不行，请从1开始连续递增。

**Comment by clarenceli** [comment]
我明白了，这个可能要在文档提示一下，不然其他童鞋可能不知道。

**Comment by ChenYilong** [comment]
ok

**Comment by ChenYilong** [comment]
已修改文档 https://github.com/leancloud/ChatKit-OC/compare/2c34126bbf2e...853f48dfc91c
