### ISSUE TITLE
关于ChatKit默认集成MWPhotoBrowser问题

### ISSUE THREAD

**Issue by xiongyoudou** [leancloud/ChatKit-OC#50]
您好，ChatKit的pods里面现在默认是集成MWPhotoBrowser的。但是因为我原来项目中就已经有导入MWPhotoBrowser库了（不是通过Pods方式），并且对MWPhotoBrowser做了很多扩展。因此现在使用了ChatKit的话会导致大量MWPhotoBrowser的代码文件重复。请问可以通过什么方法去掉ChatKit对MWPhotoBrowser自动pods导入吗？

**Comment by ChenYilong** [comment]
两种方式，你把你重写的MWPhotoBrowser以修改前缀的方式，来与原有的类区分开，
另一种：Fork ChatKit，然后注释这里： https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit.podspec#L27 ，Pod ChatKit 时指向你自己仓库

**Comment by xiongyoudou** [comment]
OK,谢谢
