### ISSUE TITLE
cocoapods install pods后出现

### ISSUE THREAD

**Issue by summer87279149** [leancloud/ChatKit-OC#51]
[!] Unable to read the license file `/Users/admin/ChatKit-OC/ChatKit-OC/Pods/CYLTableViewRowAction/LICENSE` for the spec `CYLTableViewRowAction (1.0.0)`

[!] Unable to read the license file `/Users/admin/ChatKit-OC/ChatKit-OC/Pods/CYLTableViewRowAction/LICENSE` for the spec `CYLTableViewRowAction (1.0.0)`

**Comment by ChenYilong** [comment]
CocoaPods 版本号是多少？另外可以参考这里的讨论：https://github.com/leancloud/ChatKit-OC/issues/38

**Comment by ChenYilong** [comment]
警告，可忽略。

**Comment by ChenYilong** [comment]
由于 CocoaPods 1.0版本，做了较大改动，可能造成非1.0 CocoaPods 版本下pod失败，该问题可通过升级到1.0解决。并且，我已经将Pod文件夹一并上传，现在运行Demo，已经不需要pod，如果之前遇到过安装问题，现在请重试。
