### ISSUE TITLE
收到系统消息程序crash

### ISSUE THREAD

**Issue by clarenceli** [leancloud/ChatKit-OC#54]
当收到一条系统消息的时候，程序会挂掉，因为没有peerId。

**Comment by clarenceli** [comment]
没有peerId就是invalid conversation？

**Comment by ChenYilong** [comment]
嗯，我看下

**Comment by ChenYilong** [comment]
具体挂到哪儿了，有截图没？是不是我没覆盖到系统消息这种情况

**Comment by clarenceli** [comment]
![screen shot 2016-09-01 at 10 42 41](https://cloud.githubusercontent.com/assets/6646766/18153543/dcf514a4-7030-11e6-9bbb-a28cbd13cb60.png)

**Comment by clarenceli** [comment]
![screen shot 2016-09-01 at 10 43 51](https://cloud.githubusercontent.com/assets/6646766/18153574/018df33a-7031-11e6-80d4-20455402e9cb.png)

**Comment by clarenceli** [comment]
我看到leancloud的控制台 系统消息是没有member的，应该要分开处理？

**Comment by ChenYilong** [comment]
确认下你使用的是哪种系统消息：
 [《系统对话消息》]( https://leancloud.cn/docs/realtime_v2.html#系统对话_System_Conversation_ ) 、
 [《广播消息》]( https://leancloud.cn/docs/realtime_v2.html#广播消息 )

**Comment by clarenceli** [comment]
系统对话消息

**Comment by ChenYilong** [comment]
请问系统对话，你是打算做成什么样的效果？

你是否希望系统展示在最近对话列表中？我猜你应该不会希望系统对话展示出来的吧。

我把系统对话消息筛选出来，暴露一个通知出来你监听该系统通知。你获得通知，自行处理消息，如何？

**Comment by clarenceli** [comment]
可否提供一个接口出来，假如是系统对话，可通过自己系统接口拿到的profile，传给它

**Comment by clarenceli** [comment]
我们现在的要效果其实也是参与最近对话列表，混在一起。

**Comment by clarenceli** [comment]
能否设置成一个开关，默认不开启，暴露一个通知出来，开启之后，就是参与最近对话列表。

**Comment by ChenYilong** [comment]
如果你希望展示到对话列表中的话，那么由于非单聊，非群聊，如何展示对话名称？

我这里有几个方案，你看下:

ChatKit为系统对话，设置一个固定的名称，“系统通知”，然后放在本地化文件中，APP可以通过自定义本地化文件的方式自定义，缺点是一个app所有系统对话名称一经发布就是固定的，不能修改。


还有另一种，那就按照群聊处理，读name字段，如果没有我再帮你再从本地化文件中展示“系统通知”。

**Comment by clarenceli** [comment]
有没有可能设计成一个接口，针对每一个系统对话，单独传个它

**Comment by ChenYilong** [comment]
Conversation不是有name字段吗？头像、名称展示直接按照群聊这一套来，怎么样

**Comment by clarenceli** [comment]
对喔，可以，这个大概多久才能弄好？

**Comment by ChenYilong** [comment]
10分钟

**Comment by clarenceli** [comment]
ok

**Comment by ChenYilong** [comment]
v0.7.9 已经发布，支持了系统消息展示，系统消息按照群聊处理 https://github.com/leancloud/ChatKit-OC/commit/3bc3e1f1cbe768cddc3f1466b1590b120efdc266

**Comment by clarenceli** [comment]
点击进入聊天界面，程序会挂，停在这一句conversationInvalidedHandler(conversationId, self, user, error);并且下次启动系统对话不见了

**Comment by ChenYilong** [comment]
ok,我看下

**Comment by ChenYilong** [comment]
创建一个系统对话，需要通过REST API 创建，详情见文档： [《创建一个对话》]( https://leancloud.cn/docs/realtime_rest_api.html#创建一个对话 )  ,发送一个系统消息也是通过REST-API发送，详情见文档  [《系统对话给用户发消息》]( https://leancloud.cn/docs/realtime_rest_api.html#系统对话给用户发消息 ) ，修改系统对话时，也必须使用REST-API或者直接到控制台修改。APP不支持修改。

**Comment by clarenceli** [comment]
完全走群聊这一套的话，意味着系统对话的attributes中带的头像url一定是要和ChatKit中LCCKConversationGroupAvatarURLKey定义的一致

**Comment by ChenYilong** [comment]
你的意见呢？

**Comment by ChenYilong** [comment]
是不是感觉这个字段有歧义，这个字段之前是为群聊准备的，现在又加入了单聊，可能会歧义？

**Comment by ChenYilong** [comment]
之前是 groupAvatarURL，如果改成 avatarURL，这样是不是就好一点？

**Comment by clarenceli** [comment]
还有另外一个原因就是假如后台在系统对话的attributes塞的不是groupAvatarURL，那就没法拿了。

**Comment by ChenYilong** [comment]
是的，这个方案，肯定是需要一个字段来确定头像的。

**Comment by clarenceli** [comment]
这个字段可否由我自己配置

**Comment by ChenYilong** [comment]
可以，我放到本地化文件里，到时间你可以自定义，默认就写 avatarURL。

**Comment by clarenceli** [comment]
行，还有另一问题，你可以要提供另外一个开关出来，用来开关显示名称，因为在群聊中，你默认是显示名称的

**Comment by ChenYilong** [comment]
系统对话里的系统消息，我推荐你使用自定义消息，自定义消息时，不配置昵称就好了。v0.7.11自定义字段的版本发布了，你更新下。groupAvatarURL -》 avatarURL， https://github.com/leancloud/ChatKit-OC/commit/abaee1137c7fbd9e682ee09cb4c512fe2900e207

**Comment by clarenceli** [comment]
但是系统对话又可以发普通消息，比如文本消息等等。我的意思是把普通消息的昵称去掉

**Comment by ChenYilong** [comment]
这个可以，这个功能下一版本加上。

**Comment by ChenYilong** [comment]
移到这里讨论 ：https://github.com/leancloud/ChatKit-OC/issues/60

**Comment by ChenYilong** [comment]
在做最近对话列表同步的时候，比如想达到如下效果，系统对话要做特殊处理：

> 在获取会话列表的基础上同时返回系统对话
 
https://github.com/leancloud/objc-sdk/pull/120/files

**Comment by ChenYilong** [comment]
创建系统消息方法：

 ```Objective-C
curl -X POST \
     -H "X-LC-Id: dYRQ8YfHRiILshUnfFJu2eQM-gzGzoHsz" \
     -H "X-LC-Key: ye24iIK6ys8IvaISMC4Bs5WK" \
     -H "Content-Type: application/json" \
     -d '{"name": "系统通知", "avatarURL": "http://ww1.sinaimg.cn/large/006y8lVajw1faip71wtc7j30200203ya.jpg", "sys": true}' \
     https://api.leancloud.cn/1.1/classes/_Conversation
 ```

发送全员广播：

 ```Objective-C
curl -X POST \
  -H "X-LC-Id: dYRQ8YfHRiILshUnfFJu2eQM-gzGzoHsz" \
  -H "X-LC-Key: LP6vluS4rJ8iwnkCy21FaSDS,master" \
  -H "Content-Type: application/json" \
  -d '{"from_peer": "系统消息", "message": "{\"_lctype\":-1,\"_lctext\":\"ChatKit全面支持系统广播消息，一键群发给所有用户。\",\"_lcattrs\":{\"a\":\"_lcattrs 是用来存储用户自定义的一些键值对\"}}", "conv_id": "58483a93ac502e006ce98b27"}' \
  https://leancloud.cn/1.1/rtm/broadcast 
 ```
