### ISSUE TITLE
程序运行不起来,直接crash

### ISSUE THREAD

**Issue by xueqiulou** [leancloud/ChatKit-OC#55]
![2016-09-01 10 38 29](https://cloud.githubusercontent.com/assets/13198448/18153509/8aac60ee-7030-11e6-9fbf-b4014da3f243.png)

先是在图中这里断点一下,接着就是crash了,是什么原因

-[LCCKConversationService setupSucceedMessageDatabaseWithPath:] [Line 210] database queue should not be nil !!!!
libc++abi.dylib: terminate_handler unexpectedly threw an exception

**Comment by ChenYilong** [comment]
请提供更多信息，比如控制台的日志打印，请确保你设置了APPID和APPKey。

**Comment by xueqiulou** [comment]
果然是因为注释了设置appID 和 appKey 的代码,忘了把代码放出来,谢谢啊,这么低级的错误...

**Comment by ChenYilong** [comment]
没事，有问题随时提。问题解决的话，帮忙关对应issue。

**Comment by xueqiulou** [comment]
好的
