### ISSUE TITLE
聊天发送不出去

### ISSUE THREAD

**Issue by LJW0428** [leancloud/ChatKit-OC#56]
我只是单独的发一条，没有做页面，打断点发送成功，但是在另一个帐号登录之后没有收到信息

**Comment by LJW0428** [comment]
简单的粘贴文档里面的稍微修改了一下

**Comment by ChenYilong** [comment]
贴一下日志打印，控制台里会有日志，

我看看你哪一步出错了

**Comment by LJW0428** [comment]
亲，我在项目里面只做了两个页面 一个是登录页，登录成功之后，第二个页面我直接添加了一个按钮点击之后就是上面哪个方法，我只能给你说第一步登录成功了，第二步控制台也有发送成功

**Comment by LJW0428** [comment]
你看一下是不是方法不对，还是有别的我没有注意到
我只是在Appdelegate里面注册了一下，用我自己的key，别的就先做了两个页面

**Comment by ChenYilong** [comment]
//希望能提供更详细的日志信息，打开日志的方式是在 AVOSCloud 初始化语句之后加上下面这句：

//Objective-C
#ifndef __OPTIMIZE__
    [AVOSCloud setAllLogsEnabled:YES];
#endif

//Swift
 AVOSCloud.setAllLogsEnabled(YES);

主要贴一下以 curl 开头的那个。主要是想看下网络请求，携带的参数，以及网络请求的返回值

**Comment by LJW0428** [comment]
好的

**Comment by LJW0428** [comment]
2016-09-01 16:46:37.434 SteelCat[11691:101205] [INFO] __60-[AVIMWebSocketWrapper openWebSocketConnectionWithCallback:]_block_invoke [Line 385] Open websocket connection.
2016-09-01 16:46:37.437 SteelCat[11691:101205] [DEBUG] -[AVPaasClient performRequest:success:failure:] [Line 647] 

------ BEGIN LeanCloud REST Request -------
path: /v1/route
curl: curl -i -k -X GET --compressed -H 'Accept: application/json' -H 'Content-Type: application/json; charset=utf-8' -H 'X-LC-Session: 1cc5uo7oadkdhvrcgtwls33z2' -H 'Accept-Language: zh-Hans-US;q=1, en-US;q=0.9' -H 'User-Agent: AVOS Cloud iOS-v3.3.5 SDK' -H 'X-LC-Id: pHhjTXPyYLqRXwfi0cDXIgH9-gzGzoHsz' -H 'X-LC-Prod: 1' -H 'X-LC-Sign: e8d09872e32d47cef4300295fb144c5a,1472719597435' --data-urlencode 'appId=pHhjTXPyYLqRXwfi0cDXIgH9-gzGzoHsz' --data-urlencode 'ip=true' --data-urlencode 'secure=1' "https://router-g0-push.leancloud.cn/v1/route"
------ END --------------------------------

2016-09-01 16:46:38.827 SteelCat[11691:101205] [INFO] -[AVIMWebSocketWrapper internalOpenWebSocketConnection:] [Line 561] Open websocket with url: wss://rtm56.leancloud.cn:6799/
2016-09-01 16:46:38.829 SteelCat[11691:101205] [DEBUG] __59-[AVPaasClient performRequest:saveResult:block:retryTimes:]_block_invoke [Line 570] 

------ BEGIN LeanCloud REST Response ------
path: /v1/route
cost: 1.391s
response: {
    groupId = g0;
    secondary = "wss://rtm51.leancloud.cn:6799/";
    server = "wss://rtm56.leancloud.cn:6799/";
    ttl = 3600;
}
------ END --------------------------------

2016-09-01 16:46:39.227 SteelCat[11691:100405] [INFO] -[AVIMWebSocketWrapper webSocketDidOpen:] [Line 740] Websocket connection opened.
2016-09-01 16:46:39.229 SteelCat[11691:101466] [INFO] -[AVIMWebSocketWrapper sendCommand:] [Line 684] 

------ BEGIN LeanCloud IM Out Command ------
cmd: Session
type: AVIMSessionCommand
content: <AVIMGenericCommand 0x7fe80d864050>: {
    cmd: session
    op: open
    appId: "pHhjTXPyYLqRXwfi0cDXIgH9-gzGzoHsz"
    peerId: "ljw"
    sessionMessage {
      ua: "ios/v3.3.5"
      r: false
      deviceToken: "5191f793-1e6b-4687-9f10-45fbc630c439"
    }
}
------ END ---------------------------------

2016-09-01 16:46:39.289 SteelCat[11691:100405] [INFO] -[AVIMWebSocketWrapper webSocket:didReceiveMessage:] [Line 756] 

------ BEGIN LeanCloud IM In Command ------
content: <AVIMGenericCommand 0x7fe80b5f4c50>: {
    cmd: session
    op: opened
    appId: "pHhjTXPyYLqRXwfi0cDXIgH9-gzGzoHsz"
    peerId: "ljw"
    i: 1
    sessionMessage {
      st: "tGNq5wVjSr+snsiBjhnB_g"
      stTtl: 17280
    }
}
------ END --------------------------------

2016-09-01 16:46:39.290 SteelCat[11691:101205] [INFO] -[AVIMWebSocketWrapper sendCommand:] [Line 684] 

------ BEGIN LeanCloud IM Out Command ------
cmd: Conv
type: AVIMConvCommand
content: <AVIMGenericCommand 0x7fe80b4b23e0>: {
    cmd: conv
    op: start
    peerId: "ljw"
    convMessage {
      m: "ljwljwljwljw"
      attr {
        data: "{"name":"8888888"}"
      }
    }
}
------ END ---------------------------------

2016-09-01 16:46:39.377 SteelCat[11691:100405] [INFO] -[AVIMWebSocketWrapper webSocket:didReceiveMessage:] [Line 756] 

------ BEGIN LeanCloud IM In Command ------
content: <AVIMGenericCommand 0x7fe80d956c80>: {
    cmd: conv
    op: started
    peerId: "ljw"
    i: 2
    convMessage {
      cid: "57c7eaee2e958a0068c6a9bf"
      cdate: "2016-09-01T08:46:38.943Z"
    }
}
------ END --------------------------------

**Comment by LJW0428** [comment]
这是发消息的日志
<img width="888" alt="2016-09-01 4 32 00" src="https://cloud.githubusercontent.com/assets/13958008/18161299/f2d68194-7063-11e6-84e7-f4a24280881d.png">
<img width="326" alt="2016-09-01 4 45 52" src="https://cloud.githubusercontent.com/assets/13958008/18161300/f3d2f2a8-7063-11e6-8b2c-69e1f9ae1b4c.png">
<img width="946" alt="2016-09-01 4 46 18" src="https://cloud.githubusercontent.com/assets/13958008/18161313/fe566296-7063-11e6-8710-1e7c9f156c01.png">

**Comment by LJW0428** [comment]
这是登录之后的日志

**Comment by ChenYilong** [comment]
你创建对话时，将自己的ClientId也传进去，你现在对话里只有一个人。

**Comment by LJW0428** [comment]
怎么改，文档里面就是这样写的啊
<img width="841" alt="2016-09-01 4 55 41" src="https://cloud.githubusercontent.com/assets/13958008/18161559/ff6210ee-7064-11e6-87d7-9618efa031cf.png">

**Comment by LJW0428** [comment]
我登陆的账号就是ljw，明明传了啊

**Comment by LJW0428** [comment]
到底是哪里的原因

**Comment by ChenYilong** [comment]
有没有demo，发来一个luohanchenyilong@163.com

**Comment by LJW0428** [comment]
我不知道是不是我配置的少了什么东西

**Comment by ChenYilong** [comment]
不知道，建议直接使用ChatKit，如果不是 ChatKit 的问题，就别贴在这里了，可以去论坛发帖。
