### ISSUE TITLE
对ChatKit中pods版本的建议

### ISSUE THREAD

**Issue by xiongyoudou** [leancloud/ChatKit-OC#58]
您好！
ChatKit中，默认是集成了不少其他第三方开源库的pods,并且还指定了版本号。但是因为那些库都是在不断更新的，导致ChatKit中某些新属性用不了。并且可能出现项目中其他模块需要依赖较新的pods库，而ChatKit还只是比较旧的版本，此时甚至会导致编译失败。
现在情况就是我 项目里需要用MWPhotoBrowser中MWPhoto中的新属性photoURL，但是ChatKit中指定的MWPhotoBrowser库并没有该属性

**Comment by ChenYilong** [comment]
请给出你的版本号，我升级下ChatKit依赖的库

**Comment by ChenYilong** [comment]
我的项目依赖的已经是最新版的了，见 https://github.com/mwaterfall/MWPhotoBrowser/releases

**Comment by xiongyoudou** [comment]
不好意思，MWPhotoBrowser的确是最新的了！是我这边的另一个模块依赖的MWPhotoBrowser的版本号过低！谢谢回复！
