### ISSUE TITLE
小白问题。。fetchProfilesBlock里面的userid是神马东西

### ISSUE THREAD

**Issue by mickymickymicky** [leancloud/ChatKit-OC#63]
请问下userId是干嘛的 fetchProfilesBlock传入的userId等同clientId吗
谢谢

**Comment by ChenYilong** [comment]
请参考文档：

https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit%20自定义业务.md#clientid-与-userid

以及
这里的讨论https://github.com/leancloud/ChatKit-OC/issues/17
