### ISSUE TITLE
关闭聊天服务 (closeWithCallback ) 后,刷新最近联系人列表 程序会crash

### ISSUE THREAD

**Issue by xueqiulou** [leancloud/ChatKit-OC#64]
报这个异常,打开client的时候设置过这个方法,关闭的时候为什么还要设置一遍?

*** Terminating app due to uncaught exception 'NSGenericException', 

reason: '**_You must implement `-setFetchProfilesBlock:` to allow ChatKit to get user information by user clientId_**.'

**Comment by ChenYilong** [comment]
close client时会将所有单例清空，这个方法从属的单例也会被销毁，所以切换clientId时需要重新初始化一遍，参考demo中的胶水函数invokeThisMethodAfterLogin的做法。
