### ISSUE TITLE
下载后的代码爆红错误 pod为红色

### ISSUE THREAD

**Issue by taojeff** [leancloud/ChatKit-OC#65]
刚刚用git命令下载demo到桌面后就是成下面截图的状态了，不过我还是希望博主能否不要用pod进行管理，因为这样有时候真的不是太方便我们在参考学习你们团队所开发的代码
![1](https://cloud.githubusercontent.com/assets/19642626/18236669/38bc2b7e-735b-11e6-94bc-82248d5f1a30.png)

**Comment by ChenYilong** [comment]
ok，我已经将 pod 成功后的代码第三方库的代码一并上传了上去，降低了集成的难度。你再试一试。

**Comment by ChenYilong** [comment]
问题已解决，先close了 ，有问题再open。
