### ISSUE TITLE
希望LCCKConversationListViewController开放更多的接口。

### ISSUE THREAD

**Issue by zzgo** [leancloud/ChatKit-OC#73]
首先谢谢作者的付出，很喜欢这个ChatKit。

第一点，要为`LCCKConversationListViewController`添加一个`header`。

试了下，直接通过`setViewDidLoadBlock:`这样的方法做不到，因为`LCCKBaseViewController`拿不到tableView。只有通过 `继承` LCCKConversationListViewController，重写`viewDidLoad`方法，在里面才拿得到tableView，并添加header。

是否考虑在`setViewDidLoadBlock`里给出`tableView`的参数，或者为`id类型`，让使用者可以自己转换一下`控制器类型`？

第二点，要拿到`LCCKConversationListViewController`里面的`最近联系的会话数组`conversations的信息。目前发现继承后也拿不到，不知道是否可以开放出来？

如果针对以上问题，有更好的办法解决，希望告知。谢谢

**Comment by ChenYilong** [comment]
首先对谢你对本库的肯定，

对于tableView，其实是可以访问到的，做个强制类型转换就好了：

 ```Objective-C
[secondViewController setViewDidLoadBlock:^(__kindof LCCKBaseViewController *viewController) {
        LCCKContactListViewController *conversationList = viewController;
        conversationList.tableView;
        
 ```

**Comment by zzgo** [comment]
第一个问题。。我自己的锅，在家里也是强转不行，现在试了下可以了。没问题。

第二个问题的话，`findRecentConversationsWithBlock`我昨天也在viewModel里找到了,但是有疑惑。

在这里拿conversations，然后做修改，确定不会影响到其他地方的逻辑吗？因为我看`[[LCChatKit sharedInstance] setFetchProfilesBlock`这样的设置，都是影响全部的。比如我这里设置了之后，LCCKConversationListViewModel 里 `- (void)refresh`的逻辑是不是就会失效

**Comment by ChenYilong** [comment]
请问你打算做什么修改，请详细描述下，比如你事打算为Conversations添加内容，还是直接修改其中一些Conversation的属性？

**Comment by zzgo** [comment]
只是单纯获取一下Conversations，不做修改。

我要拿每个人的头像，然后在tableView的顶部展示(其实我觉得列表里每个cell已经有头像了，这样都重复了，设计师的脑洞我不懂)。

**Comment by ChenYilong** [comment]
不修改就没问题，ChatKit 中获取对话列表都是直接读的本地的数据库内容，如果你想修改也是可以的，直接修改本地数据库。LCCKConversationListService 里面有增删改查。

**Comment by zzgo** [comment]
OK,完美。
