### ISSUE TITLE
这里貌似会循环引用.

### ISSUE THREAD

**Issue by m8282823** [leancloud/ChatKit-OC#74]
![3cba7113-c68e-48b2-b55d-07456449d72d](https://cloud.githubusercontent.com/assets/11418004/18336356/0bde48ac-75b9-11e6-83e2-890f78352056.png)
![57e3de38-49ab-4ea3-ac30-30e9316a7095](https://cloud.githubusercontent.com/assets/11418004/18336357/0cd104d4-75b9-11e6-9b03-23977f96212c.png)

**Comment by ChenYilong** [comment]
对，今天会发版修复下。

**Comment by ChenYilong** [comment]
已修复 https://github.com/leancloud/ChatKit-OC/commit/bdd1c3e15767eaac28d60273bd72f944c9fa1a5c
