### ISSUE TITLE
when pod install from directory /Documents/opensource/ChatKit-OC-master/Chat-OC, I encounter the warning: Unable to read the license file `/Users/leesam/Documents/opensource/ChatKit-OC-master/ChatKit-OC/Pods/CYLTableViewRowAction/LICENSE` for the spec `CYLTableViewRowAction (1.0.0)`

### ISSUE THREAD

**Issue by uhuo** [leancloud/ChatKit-OC#75]
I am a greenbird, so there is a lot of issues and problems when I learn. Although I copy the LICENSE file from ChatKit-OC-master to the directory ChatKit-OC/Pods/CYLTableViewRowAction/  could solve the problem, but when I open the ChatKit-OC.xcworkspace, there is a lot of errors.

**Comment by uhuo** [comment]
Here is my Podfile:
pod 'ChatKit'
pod "CYLTableViewRowAction", "1.0.0"

**Comment by ChenYilong** [comment]
Can you show me your error?

**Comment by uhuo** [comment]
<img width="246" alt="2016-09-08 9 18 42" src="https://cloud.githubusercontent.com/assets/11812739/18350799/2bfa93e2-760a-11e6-9ec3-9896c596de6e.png">

**Comment by uhuo** [comment]
<img width="1037" alt="2016-09-08 9 26 53" src="https://cloud.githubusercontent.com/assets/11812739/18351094/5a3c4132-760b-11e6-955c-0f33c84d87c5.png">

**Comment by ChenYilong** [comment]
Do not forget to add this Lib for demo:

https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit-OC/Podfile

**Comment by uhuo** [comment]
Coming from china, I learn iOS by myself. How to add this Lib?

**Comment by uhuo** [comment]
Do you mean I should replace the Podfile with this?

**Comment by ChenYilong** [comment]
Ref :  https://guides.cocoapods.org/using/using-cocoapods.html

**Comment by uhuo** [comment]
I replace the Podfile with this one, the errors still exist when I compile the project.

**Comment by ChenYilong** [comment]
you maybe not pod CYLTabBarController from you error info.

**Comment by uhuo** [comment]
I download your project, touch file of Podfile under directory ChatKit-OC-master, vi Podfile and add those pods. But I run pod install under directory ChatKit-OC-master/ChatKit-OC.
I exactly copy your Podfile, it does indeed contain the line: pod 'CYLTabBarController'.

**Comment by ChenYilong** [comment]
If you just want to run my demo, there is no need to pod.  Try download the newest Project, I've uploaded all the third part libs,
Ref : https://github.com/leancloud/ChatKit-OC/commit/747ab4b6e118b6a1884b9fe18e8d2029013aa07b
