### ISSUE TITLE
"LCChatKit.h" file not found after pod ChatKit 0.7.14

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#76]
pod ChatKit 更新到0.7.14之后.
LCChatKitExample 文件内报错."LCChatKit.h" file not found,
同时Swift Objective-C桥接文件失联(项目是Swift) : failed to import bridging header "......"

**Comment by ChenYilong** [comment]
你上一个版本的版本号是多少？

**Comment by ChenYilong** [comment]
这个应该不是库的问题，是Demo import时出了问题，Ref： https://github.com/leancloud/ChatKit-OC/compare/e12f959f3ed6...0f3f5d877dcf

**Comment by Seppuu** [comment]
0.6.0

**Comment by Seppuu** [comment]
#if __has_include(<ChatKit / LCChatKit.h>) 改成 #if __has_include(<ChatKit/LCChatKit.h>)之后#import "LCChatKit.h"ok了. 
但是,LCChatKitExample+Setting.h 文件#import "MWPhotoBrowser.h"报错.MWPhotoBrowser.h file not found

**Comment by ChenYilong** [comment]
像这样注释掉就好了：https://github.com/leancloud/ChatKit-OC/compare/0f3f5d877dcf...d7287d61b049

**Comment by Seppuu** [comment]
好了.
