### ISSUE TITLE
LCCKUserSystemService 启动app时crash.

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#78]
- (void)setUser:(id<LCCKUserDelegate>)user forClientId:(NSString *)clientId 
{
    NSString *clientId_ = [clientId copy];
    if (!clientId_) {
        return;
    }

//新的app加载,在这个地方中断了.请问会什么原因.
    **dispatch_async(self.isolationQueue, ^(){**
        if (!user) {
            [self.cachedUsers removeObjectForKey:clientId_];
        } else {
            [self.cachedUsers setObject:user forKey:clientId_];
        }
    });

}

**Comment by ChenYilong** [comment]
你说的中断，是指crash？

**Comment by Seppuu** [comment]
是的.

**Comment by ChenYilong** [comment]
是必现的吗？还是偶尔出现，我这边的运行Demo没问题。

**Comment by Seppuu** [comment]
每次都是.

**Comment by ChenYilong** [comment]
Demo发我，我帮你找下原因  luohanchenyilong@163.com

**Comment by Seppuu** [comment]
已经发过去了.

**Comment by ChenYilong** [comment]
ok

**Comment by ChenYilong** [comment]
v0.7.15已发布，修复了，请更新下。
