### ISSUE TITLE
胶水函数

### ISSUE THREAD

**Issue by helloworlderly** [leancloud/ChatKit-OC#80]
问个很不成熟的问题，什么叫作胶水函数，有哪位大神可以告知一二么？？？小弟之前从来没听过这个词，，不是很能理解是做什么用的

**Comment by ChenYilong** [comment]
就是方便你集成Lib时做的演示函数，就好像胶水，把 Lib 和 你的 APP 连接起来。

**Comment by ChenYilong** [comment]
比如我们可以这样说：

C/Objective-C语言中的JavaScript Bindings 是介于本地代码(C or Objective-C)和 JavaScript(JS)代码之间的“胶水”代码(封装代码)

**Comment by ChenYilong** [comment]
不知你是否理解，不理解的话，可以再打开issue。

**Comment by zhouxincheng** [comment]
解释的很清楚  谢谢
