### ISSUE TITLE
关于多终端同一账号消息同步问题

### ISSUE THREAD

**Issue by XiaoSuiFeng** [leancloud/ChatKit-OC#81]
这个问题是已知问题，场景设备A B 同时登录一个账号，B在后台，A接受N条消息，B到前台后，应该也能看到消息， 但是如果保证消息不丢失，而且不重复拉取数据呢，这是个复杂的问题，有好的方案或者sdk修改后告知下，谢谢，我考虑 AVTypedMessage能不能添加一个字段lastMessageId ,下一条消息记录上一条消息的id,在非暂态消息，才用这个，每次从本地数据库读取数据，发现有不一致的就断掉，从服务器拉取N条消息.

**Comment by ChenYilong** [comment]
我这里有一个方案，

 1. 在每次用户打开App后，拿到本地数据库里消息记录里的最后一条消息localLastMessageTimestamp，
 2. 先将本地所有对话进行FetchConversation操作，
 3. 因为每个Conversation里都有一个字段叫lm，也就是lastMessage的时间戳，然后遍历一遍所有对话的lm字段，跟本地数据库里的最后一条消息的时间戳做对比，找出所有还有新消息的对话，
 4. 挨个进行查询从localLastMessageTimestamp之后的所有消息，并插入数据库。


这样就可以达到多端登录依然不丢消息的目的。

**Comment by XiaoSuiFeng** [comment]
好的，我会在每次leancloud连接成功，先拿到本地所有的会话，然后根据会话的lastMessageAt 查询之后的消息，但是查询函数用哪个啊，你们没有公开啊
- (void)queryMessagesBeforeId:(NSString *)messageId
                    timestamp:(int64_t)timestamp
                        limit:(NSUInteger)limit
                     callback:(AVIMArrayResultBlock)callback  这个是查询之前的，我要查询之后的

**Comment by XiaoSuiFeng** [comment]
这种方案 昨天也考虑了

**Comment by ChenYilong** [comment]
![](http://ww3.sinaimg.cn/large/006y8lVajw1f7ne4v3y86j30bi0kg0ux.jpg)

如上图所示，右边的有一排时间戳，取最新的时间戳，

然后 查询接口，如下所示，可以拿到符合条件的所有Conversations，，然后依次遍历queryMessage

 ```Objective-C
 AVIMConversationQuery *query = [[LCCKSessionService sharedInstance].client conversationQuery];
查询条件
    query.cachePolicy = kAVCachePolicyNetworkElseCache;
    query.limit = 1000;  // default limit:10
    [query findConversationsWithCallback: ^(NSArray *objects, NSError *error) {}];
 ```

**Comment by ChenYilong** [comment]
这个逻辑，也会在ChatKit里实现下，稍后发布。

**Comment by XiaoSuiFeng** [comment]
我是用的CDChatManager 我懂你的意思了，先通过fetch 查询到该会话的最后消息time ,然后向前查找，- (void)queryMessagesBeforeId:(NSString *)messageId
                    timestamp:(int64_t)timestamp
                        limit:(NSUInteger)limit
                     callback:(AVIMArrayResultBlock)callback; 调用这个就可以了，好的，谢谢，我只要query就行了，你们idk有数据存储操作，不会有重复数据插入吧，数据库能保证，但是我这个limit传多少合适，耗流量啊

**Comment by ChenYilong** [comment]
支持从时间戳拉取消息。

**Comment by XiaoSuiFeng** [comment]
我意思是假如有30条消息，messageId 传nil  timestamp 传会话的lastMessageAt limit 传10 我获取10条数据，在消息详情支持下拉，能不能把丢失的20消息获取下来，貌似不行。如果limit传100，肯定可以拉取，但是耗流量

**Comment by ChenYilong** [comment]
limit 不传，只传时间戳，拉取时间戳之后的所有消息，只有这样才能保证不丢消息。现在的同步方案与下拉刷新无关，同步后，消息就会保存在数据库了，下拉刷新时优先读的本地缓存，可以不走网络了。

**Comment by XiaoSuiFeng** [comment]
我问下，如果1000条消息，这样虽然不丢消息了，因为从后台到前台leanchat会重练，我只能在网络连接成功，拉取消息，流量不大吧

**Comment by XiaoSuiFeng** [comment]
消息超过1000条很正常，也有可能丢失，接口最多不是返回1000条吗

**Comment by ChenYilong** [comment]
@leancloud/push

**Comment by ChenYilong** [comment]
这个问题，就是回到你在群里问的这个问题了，原则上你只需要拉10条，后续的拉取以及填洞操作，应该就只需要 SDk 进行判断处理了，这个我看下是不是SDK的 bug：

![](http://ww4.sinaimg.cn/large/006y8lVajw1f7nfogmyxpj30yi1pcn8n.jpg)

![](http://ww4.sinaimg.cn/large/006y8lVajw1f7nfoguselj30qo0zk782.jpg)

**Comment by ChenYilong** [comment]
ChatKit 0.8.11 最新版本已经发布，更新日志 https://github.com/leancloud/ChatKit-OC/releases/tag/0.8.11
