### ISSUE TITLE
从点击推送首次打开进入App时 崩溃. ChatKit 0.7.13 

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#82]
![image](https://cloud.githubusercontent.com/assets/12640162/18382087/0fd38dce-76b2-11e6-8a07-8a07c5e2d500.png)
推送来自LeanCloud在线发送.点击进入app,在这里发生奔溃.并且,在此之前,我没有对推送数据做接受处理.普通情况下进入App,成功.

**Comment by ChenYilong** [comment]
推送来自LeanCloud在线发送？

这句话怎么理解？在线发送一个推送？还是在线发送一个message？

请将发送的具体消息或推送，贴出来

**Comment by Seppuu** [comment]
{
  "updatedAt": "2016-09-09T08:23:00.683Z",
  "where": {
    "query": {
      "deviceType": "ios"
    },
    "sort": {
      "createdAt": 1
    }
  },
  "push-time": null,
  "prod": "dev",
  "notificationId": "i9jBYs1Ddp2TGRqC",
  "createdAt": "2016-09-09T08:22:43.221Z",
  "msg": {
    "alert": "项目计划提醒 徐添翼",
    "notice_type": "project_plan",
    "notice_id": "8",
    "_expiration_time": "2016-09-16T06:41:56.659Z"
  },
  "successes": 20,
  "status": "done",
  "devices": 20,
  "pushedAt": "2016-09-09T08:22:44.059Z",
  "through?": null
}

**Comment by ChenYilong** [comment]
你在线发送了这样一条推送内容，

然后，app在后台时，你点击后台推送，进入app时会crash？

**Comment by Seppuu** [comment]
app在后台时，你点击后台推送，进入app时不会crash. 是在第一次进入的时候.(didFinishLaunchingWithOptions)crash.

**Comment by ChenYilong** [comment]
？我怎么听你的描述，感觉意思都一样，不都是点击通知栏里的推送进入的吗？怎么点击推送，还分第一次和第二次？

**Comment by ChenYilong** [comment]
最新版本是 v0.7.15，请升级下。

**Comment by Seppuu** [comment]
发生崩溃的情况是:App不在后台运行.是通过点击了推送消息,进而打开了App.这是首次.
当APP,是手动打开,退至后台的情况下.此时,从推送进入App.正常.

**Comment by ChenYilong** [comment]
怀疑这个问题，跟上一个你说的crash，是一个原因

**Comment by Seppuu** [comment]
我更新一下.看看.

**Comment by Seppuu** [comment]
v0.7.15 中这个问题也存在.应该不是上一个问题的原因.上一个原因发生在[[self sharedInstance] exampleInit];中设置用户体系那.
![image](https://cloud.githubusercontent.com/assets/12640162/18383630/0e53dce0-76b9-11e6-96f5-529b2675a902.png)

**Comment by ChenYilong** [comment]
ok，我看下

**Comment by ChenYilong** [comment]
把这个方法注释掉


 ```Objective-C
+ (void)invokeThisMethodInApplication:(UIApplication *)application
         didReceiveRemoteNotification:(NSDictionary *)userInfo
 ```

**Comment by Seppuu** [comment]
注释掉上面的方法,问题依然存在.但是,我确认了,我的问题和ChatKit无关.我没有了解清楚ios推送打开App的规则.不好意思,我准备关闭issue了.

**Comment by ChenYilong** [comment]
好的，这个issue 跟 ChatKit 无关，先关闭了。
