### ISSUE TITLE
ChatKit/UITableViewRowAction.m line:25 #error "JZTableViewRowAction must be compiled under iOS8 SDK at least"

### ISSUE THREAD

**Issue by hbxn740150254** [leancloud/ChatKit-OC#91]
报错 ChatKit/UITableViewRowAction.m line:25 #error "JZTableViewRowAction must be compiled under iOS8 SDK at least" 说 要在8.0以下编译，是不是 由于我pod 版本的时候 platform :ios, '8.0'，版本 是8.0，因此，也就报了这个错了吧，我把这个报错的宏给注释了，不影响其他功能吧？
#error "JZTableViewRowAction must be compiled under iOS8 SDK at least"
麻烦你们了，感激不尽LeanClound！

另外！还发现一个问题：
pod 'ChatKit' 后ChatKit文件夹的内容 和 从ChatKit-OC这个项目 Clone过来的ChatKit文件夹的内容相差有点大啊，会不会影响 某些功能呢？ 是因为pod 的那个版本低些吗？还是你们 没更新cocoapod上的 'ChatKit'版本，因为 实在 不想 手动集成，太麻烦，涉及到很多非ARC文件需要加flag，因此就采用了pod集成，却发现 pod集成文件 与 Clone过来的ChatKit文件夹的内容有点大，就在 犹豫，是不是哪里不对啊！
![02c682bb-0e66-4cae-aa7e-15cec5844621](https://cloud.githubusercontent.com/assets/17949980/18613946/4b87b7bc-7db7-11e6-83f9-153ae488366b.png)

**Comment by ChenYilong** [comment]
你Pod的 ChatKit 的版本太低了，请使用

pod update 

命令进行，保证pod下来的，是最新版本的。最新版本是v0.7.16。

关于报错的问题，也是版本太旧的原因。升级到最新版就可以得到解决，另请参考： [常见问题](https://github.com/leancloud/ChatKit-OC#常见问题)

**Comment by ChenYilong** [comment]
升级版本就能解决，先关闭了。
