### ISSUE TITLE
如何在外面设置第一次创建聊天，不发送欢迎语

### ISSUE THREAD

**Issue by whytimber** [leancloud/ChatKit-OC#92]
如何在外面设置第一次创建聊天，不发送欢迎语？
需要写一个category 重写 sendWelcomeMessageIfNeeded:吗？
有没有更好的方式不改chatkit 库

**Comment by whytimber** [comment]
写一个category 重写 sendWelcomeMessageIfNeeded:吗？

**Comment by ChenYilong** [comment]
这个当时是有考虑的。

具体的步骤如下：

 1. 自定义本地化文件，
  自定义本地化文件的方式参考  [这里](https://github.com/leancloud/ChatKit-OC/blob/master/ChatKit%20自定义样式.md#默认UI资源包位置) 

 2. 修改对应的欢迎语

 将

 ```Objective-C
"GroupWelcomeMessage" = "大家好";
"GroupWelcomeMessageWithNickName" = "大家好，我是";
 ```

改为


 ```Objective-C
"GroupWelcomeMessage" = "";
"GroupWelcomeMessageWithNickName" = "";
 ```

 这样就不会发送欢迎语了。

**Comment by Seppuu** [comment]
试了一下，自定义UI资源包的方式，修改了"SingleWelcomeMessage" = "";但是依然显示。“我们已经是好友啦，一起来聊天吧！”ChatKit中对应的资源包需要删除吗?

**Comment by ChenYilong** [comment]
以同样的方式改下本地化文件，这句话对应的： "我们已经是好友啦，一起来聊天吧！"。

**Comment by ChenYilong** [comment]
另外 Bubble 文件会有编译缓存，不清楚缓存，本地化修改不会生效。

**Comment by Seppuu** [comment]
清理了缓存,重新安装了app,依然显示ChatKit中的对应的资源包里面的： "我们已经是好友啦，一起来聊天吧！"。

**Comment by whytimber** [comment]
生效了

**Comment by zzgo** [comment]
@Seppuu 你后来生效了吗？我也是一样，复制了other.bundle，修改名为 `CustomizedChatKitOther.bundle`，重新在另一台电脑上编译,都没有生效。

**Comment by ChenYilong** [comment]
@zzgo 这个是一个Bug，已经修复了，详情见这里的讨论： https://github.com/leancloud/ChatKit-OC/issues/146

**Comment by ChenYilong** [comment]
CocoaPods 已经更新到V0.7.21，请更新

**Comment by Seppuu** [comment]
更新到0.7.22.依然没有生效.

**Comment by ChenYilong** [comment]
文档已更新，之前文档的命名规则有问题：https://github.com/leancloud/ChatKit-OC/issues/223
