### ISSUE TITLE
v0.7.15 LCCKConversationListViewController 数据源为空时.提示无内容.

### ISSUE THREAD

**Issue by Seppuu** [leancloud/ChatKit-OC#95]
在LCCKConversationListService中看到.TODO:
![image](https://cloud.githubusercontent.com/assets/12640162/18665459/f68dc89c-7f59-11e6-944b-deebe8e85981.png)
请问这个viewForNoData什么时候能出来?当前版本为v0.7.15

**Comment by ChenYilong** [comment]
我看过你的代码，你是使用的继承方式，那么你就可以直接使用这个库，来做 https://github.com/dzenbot/DZNEmptyDataSet 。

**Comment by Seppuu** [comment]
好的.
