### ISSUE TITLE
iOS10真机 LCCKConversationViewController聊天界面下点击➕按钮 在弹出键盘和表情互相切换时候，切换动画从左飞起，iOS9没这样问题

### ISSUE THREAD

**Issue by hbxn740150254** [leancloud/ChatKit-OC#99]
iOS10真机 LCCKConversationViewController聊天界面下点击➕按钮 在弹出键盘和表情互相切换时候，切换动画从左飞起，iOS9没这样问题，只有iOS10 和 Xcode8 + iOS10模拟器出现这样的现象, 麻烦有空看下，谢谢LeanCloud～～

**Comment by ChenYilong** [comment]
iOS正式版本，还是beta版本，如果是beta，请升级到正式版。

**Comment by hbxn740150254** [comment]
手机系统是正式版本，iOS10.0.1，并且iOS10的模拟器运行此Demo也有同样的问题，切换动画很乱，一直从左往右跳

**Comment by clarenceli** [comment]
我也遇到同样问题，除此之外，每次点击键盘出来的时候，聊天记录都会上下闪。 @ChenYilong

**Comment by yyl1989726** [comment]
确实有这个问题，设计到另一个动画是键盘改变时，tableview的动画，上半部门会先被遮盖住，再显示的问题

**Comment by ChenYilong** [comment]
新版本已经发布，已经修复，请更新下： 0.8.4。
